### ISSUE TITLE
Dockerfile should expose port 8082 instead of 8081

### ISSUE THREAD

**Issue by xanonid** [jacksontj/promxy#126]
Default is 8082, but Dockerfile uses 8081.

https://github.com/jacksontj/promxy/blob/7605b382ec5393b17b69ab1fc9d8ed75a99a4226/Dockerfile#L9

**Comment by jacksontj** [comment]
@xanonid thanks for the report! Fixed in #127

**Comment by jacksontj** [comment]
I've also created a [new release](https://github.com/jacksontj/promxy/releases/tag/v0.0.32) with the change
