### ISSUE TITLE
Query result may incomplete

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#14]
It's not clear form README, but I read the code and found that the server_groups means the HA pair of prometheus, which run with the same config. And current implementation is reading from only one server in the server group.
*If I'm wrong, please correct me and ignore below.*

Because prometheus don't support clustering or bulk import, it may lack some time series data due to server temporally down or reloading config. The best practice is running 2 prometheus with same config to provide HA. The single prometheus may lack some data in query result, but we can get all data if we combined the HA pair result.

Because current implementation read from only one server in the server group, the result may be incomplete. I suggest make it read at least 2 servers in server group and combine the result.

**Comment by jacksontj** [comment]
First off, thanks for reporting the issue! Documentation is important, but sometimes hard to get right on the first go around.

> It's not clear form README, but I read the code and found that the server_groups means the HA pair of prometheus, which run with the same config. And current implementation is reading from only one server in the server group.

Partially correct. A servergroup is a set of prometheus hosts which are "configured the same". Promxy will actually query every host in the server group (until #3 is done) to merge the datapoints together.

> The best practice is running 2 prometheus with same config to provide HA. 

Exactly, and this is what a `ServerGroup` is -- a group of prometheus servers with the same config.


I've opened #15 with a FAQ entry to address this, mind taking a look to make sure its clear?

**Comment by Wing924** [comment]
@jacksontj 
That's great! Thank you! This tool is what I'm looking for.

**Comment by jacksontj** [comment]
glad to hear it! If you have any other questions/concerns/comments definitely let me know! I'll go ahead and merge in that README update.
