### ISSUE TITLE
Trickster's "query=up" healthcheck doesn't work with Promxy

### ISSUE THREAD

**Issue by raffraffraff** [jacksontj/promxy#167]
See Trickster issue: https://github.com/Comcast/trickster/issues/225

They've recently modified the /health endpoint to use `query?query=up`, and presumably this works when Trickster is caching a Prometheus service. However, when Trickster caching for Promxy, this health check returns `HTTP/1.1 405 Method Not Allowed`. Promxy logs the following when Trickster's /health is used:
`172.17.0.1 - - [13/Jun/2019 13:57:04] "GET /api/v1/query?query=up HTTP/1.1 405 19" 0.000024`

However, if I hit Promxy _directly_ with this query it 'works'. I get a `200`:
```
172.17.0.1 - - [13/Jun/2019 13:46:21] "GET /api/v1/query HTTP/1.1 200 1371142" 1.499354 query=up
```
...followed by a bunch of these, one for each endpoint, with different ranges.:
```
http://prometheus-scraper:9090" api=GetValue end="2019-06-13 13:47:10.886 +0000 UTC" matchers="[__name__=\"up\"]" start="2019-06-13 13:42:10.886 +0000 UTC
```
..and the curl command produces about 1.5M of results (all "up" metrics for the various prometheus endpoints)

**Comment by raffraffraff** [comment]
Closing, because Trickster

**Comment by jacksontj** [comment]
@raffraffraff I'm glad they are adding config for this, that *is* an excessively expensive call :)
