### ISSUE TITLE
Promxy on Kubernetes

### ISSUE THREAD

**Issue by Swetad90** [jacksontj/promxy#187]
Hi,

I have the following queries on usage of Promxy:
1. I couldn't find the docker image for promxy. Do I have to build the image from the source code?

2. How does promxy handle multiple Prometheus instance in a single K8s cluster. For my usecase, I have a cluster with 2 replicas. If I deploy promxy in the same cluster,  do I have to use kubernetes_sd_config to discover the 2 pods ? Promxy is expected to create a proxy between them?

**Comment by jacksontj** [comment]
1. The image is linked on the readme (here for convenience: https://quay.io/repository/jacksontj/promxy)

2. Promxy is that aggregating proxy you describe. You'd need to configure promxy's [ServerGroups](https://github.com/jacksontj/promxy#what-is-a-servergroup) based on the layout of data, but based on what you describe if both pods are the same data just put the 2 in the same servergroup (presumably using kubernetes_sd_config) and you should be all set!

**Comment by jacksontj** [comment]
Another thing that might be helpful, there is an [example k8s manifest](https://github.com/jacksontj/promxy/blob/master/deploy/k8s/promxy.yaml) in the repo that you can modify.

**Comment by Swetad90** [comment]
` 
    ## Regular prometheus configuration
    ##
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy_k8s
    ### Promxy configuration

    promxy:
      server_groups:
      - kubernetes_sd_configs:
        - api_server: https://172.xx.xx.xx:6443
          role: pod
          tls_config:
            insecure_skip_verify: true
            #ca_file: /etc/prometheus/ca.crt
          bearer_token_file: /etc/prometheus/token
          namespaces:
            names:
              - monitoring
        tls_config:
          insecure_skip_verify: true
          #ca_file: /etc/prometheus/ca.crt
        bearer_token_file: /etc/prometheus/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            regex: ()
            target_label: __meta_kubernetes_pod_annotation_prometheus_io_path
            replacement: /metrics
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_number, __meta_kubernetes_pod_annotation_prometheus_io_path]
            target_label: __metrics_path__
            regex: (.+);(.+);(.+);(.+)
            replacement: /api/v1/namespaces/$1/pods/$2:$3/proxy$4
          - target_label: __address__
            replacement: 172.xx.xx.xxx:6443
       labels:
         sg: k8s_9090
       anti_affinity: 10s`

But I kept on getting error about the line "labels:" stating that its missing "-". 
If I removed that, deployment went through fine. I see the pods are up and healthy.

But Grafana dashboards display as no datapoints.
Promxy logs however displays all are HTTP 200.

`10.233.64.1 - - [02/Jul/2019 17:53:40] "GET /api/v1/query_range HTTP/1.1 200 87" 0.000452 end=1562090040&step=30&query=irate%28prometheus_tsdb_compactions_failed_total%7Bjob%3D%22prometheus%22%7D%5B5m%5D%29&start=1562086410
10.233.64.1 - - [02/Jul/2019 17:53:40] "GET /api/v1/query_range HTTP/1.1 200 87" 0.000310 query=irate%28prometheus_tsdb_compactions_total%7Bjob%3D%22prometheus%22%7D%5B5m%5D%29&start=1562086410&end=1562090040&step=30
10.233.64.1 - - [02/Jul/2019 17:53:40] "GET /api/v1/query_range HTTP/1.1 200 87" 0.000438 step=30&query=irate%28prometheus_tsdb_compactions_triggered_total%7Bjob%3D%22prometheus%22%7D%5B5m%5D%29&start=1562086410&end=1562090040
10.233.64.1 - - [02/Jul/2019 17:53:40] "GET /api/v1/query_range HTTP/1.1 200 87" 0.000335 query=rate%28prometheus_tsdb_reloads_total%7Bjob%3D%22prometheus%22%7D%5B5m%5D%29&start=1562086410&end=1562090040&step=30
10.233.64.1 - - [02/Jul/2019 17:53:40] "GET /api/v1/query_range HTTP/1.1 200 87" 0.000366 query=rate%28prometheus_tsdb_reloads_failures_total%7Bjob%3D%22prometheus%22%7D%5B5m%5D%29&start=1562086410&end=1562090040&step=30
10.233.64.1 - - [02/Jul/2019 17:53:40] "GET /api/v1/query_range HTTP/1.1 200 87" 0.000280 query=prometheus_engine_query_duration_seconds%7Bjob%3D%22prometheus%22%2C+quantile%3D%220.99%22%7D&start=1562086410&end=1562090040&step=30
10.233.64.1 - - [02/Jul/2019 17:53:41] "GET /api/v1/query_range HTTP/1.1 200 87" 0.003452 query=max%28prometheus_rule_group_duration_seconds%7Bjob%3D%22prometheus%22%7D%29+by+%28quantile%29&start=1562086410&end=1562090040&step=30
10.233.64.1 - - [02/Jul/2019 17:53:41] "GET /api/v1/query_range HTTP/1.1 200 87" 0.003117 query=rate%28prometheus_rule_group_iterations_total%7Bjob%3D%22prometheus%22%7D%5B5m%5D%29&start=1562086410&end=1562090040&step=30
10.233.64.1 - - [02/Jul/2019 17:53:41] "GET /api/v1/query_range HTTP/1.1 200 87" 0.008867 start=1562086410&end=1562090040&step=30&query=rate%28prometheus_rule_group_iterations_missed_total%7Bjob%3D%22prometheus%22%7D%5B5m%5D%29
`

I am using the default Prometheus 2.0 stats dashboard

**Comment by Swetad90** [comment]
I have removed the labels parameters for now and deployed. Any idea what could be causing the grafana datapoints to be empty?

The queries work when executed on the Prometheus instance

**Comment by jacksontj** [comment]
That I'm not sure about, but my first guess would be something to do with your relabel_config; if you enable debug logging on promxy it should make it easier to figure out.

**Comment by Swetad90** [comment]
I use similar relabel_config in my Prometheus instance to get the pods metrics. My assumption was to use similar configs for promxy too to discover the pods.

I also enabled the log level to debug but I don't see much helpful data:

`10.233.64.1 - - [02/Jul/2019 18:57:42] "GET /api/v1/query_range HTTP/1.1 200 87" 0.003235 query=prometheus_tsdb_wal_corruptions_total%7Bjob%3D%22prometheus%22%7D&start=1562090220&end=1562093880&step=60
10.233.64.1 - - [02/Jul/2019 18:57:42] "GET /api/v1/query_range HTTP/1.1 200 87" 0.001239 start=1562090250&end=1562093880&step=30&query=prometheus_tsdb_head_chunks%7Bjob%3D%22prometheus%22%7D
10.233.64.1 - - [02/Jul/2019 18:57:42] "GET /api/v1/query_range HTTP/1.1 200 87" 0.006457 query=sum%28irate%28prometheus_tsdb_head_samples_appended_total%7Bjob%3D%22prometheus%22%7D%5B5m%5D%29%29&start=1562090250&end=1562093880&step=30
10.233.64.1 - - [02/Jul/2019 18:57:42] "GET /api/v1/query_range HTTP/1.1 200 87" 0.001454 query=sum%28process_open_fds%7Bjob%3D%22prometheus%22%7D%29&start=1562090250&end=1562093880&step=30
time="2019-07-02T18:57:42Z" level=debug msg="AggregateExpr sum(irate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\"}[5m]))"
time="2019-07-02T18:57:42Z" level=debug msg="call irate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\"}[5m]) vector"
time="2019-07-02T18:57:42Z" level=debug msg=Select matchers="[job=\"prometheus\" __name__=\"prometheus_tsdb_wal_corruptions_total\"]" selectParams="&{1562089920000 1562093880000 60000 }" took="36.763µs"
time="2019-07-02T18:57:42Z" level=debug msg=Select matchers="[job=\"prometheus\" __name__=\"prometheus_tsdb_head_chunks\"]" selectParams="&{1562089950000 1562093880000 30000 }" took="17.066µs"
time="2019-07-02T18:57:42Z" level=debug msg="AggregateExpr sum(process_open_fds{job=\"prometheus\"})"
time="2019-07-02T18:57:42Z" level=debug msg=Select matchers="[job=\"prometheus\" __name__=\"process_open_fds\"]" selectParams="&{1562089950000 1562093880000 30000 sum}" took="13.129µs"
time="2019-07-02T18:57:42Z" level=debug msg="AggregateExpr sum(process_resident_memory_bytes{job=\"prometheus\"})"
time="2019-07-02T18:57:42Z" level=debug msg=Select matchers="[job=\"prometheus\" __name__=\"process_resident_memory_bytes\"]" selectParams="&{1562089950000 1562093880000 30000 sum}" took="14.644µs"
10.233.64.1 - - [02/Jul/2019 18:57:42] "GET /api/v1/query_range HTTP/1.1 200 87" 0.002301 query=sum%28process_resident_memory_bytes%7Bjob%3D%22prometheus%22%7D%29&start=1562090250&end=1562093880&step=30
time="2019-07-02T18:57:42Z" level=debug msg="AggregateExpr sum(prometheus_tsdb_head_active_appenders{job=\"prometheus\"})"
time="2019-07-02T18:57:42Z" level=debug msg=Select matchers="[job=\"prometheus\" __name__=\"prometheus_tsdb_head_active_appenders\"]" selectParams="&{1562089950000 1562093880000 30000 sum}" took="26.948µs"
time="2019-07-02T18:57:42Z" level=debug msg=Select matchers="[job=\"prometheus\" __name__=\"process_virtual_memory_bytes\"]" selectParams="&{1562089950000 1562093880000 30000 }" took="84.203µs"
10.233.64.1 - - [02/Jul/2019 18:57:42] "GET /api/v1/query_range HTTP/1.1 200 87" 0.002699 query=process_virtual_memory_bytes%7Bjob%3D%22prometheus%22%7D&start=1562090250&end=1562093880&step=30
time="2019-07-02T18:57:42Z" level=debug msg="AggregateExpr max by(job) (scrape_duration_seconds)"
`

**Comment by Swetad90** [comment]
Also, if not in the way I have used, what other way do you suggest to deploy promxy with in K8s to discover the prometheus instances ?

**Comment by jacksontj** [comment]
Ah, I think there's a misunderstanding there. Promxy isn't discovering the pods, its discovering the prometheus hosts. Promxy is simply an aggregator, so it queries the prometheus hosts to stitch the data together, so the discovery config there should target all the prometheus hosts (not all things with exporters).

**Comment by Swetad90** [comment]
So I understand it right, promxy cannot aggregate 2 replicas of Prometheus deployment. But rather 2 deployment of prometheus.

I have to run 1 replica and have 2 deployments. I can expose each on separate NodePort and give that as static configs in promxy configuration ?

**Comment by jacksontj** [comment]
> So I understand it right, promxy cannot aggregate 2 replicas of the same Prometheus deployment. But rather 2 deployment of prometheus.

Promxy can aggregate both different shards of data (different replica sets) as well as replicas within the set.

From the configuration:
```
  - kubernetes_sd_configs:
    - api_server: https://172.xx.xx.xx:6443
      role: pod
      tls_config:
        insecure_skip_verify: true
        #ca_file: /etc/prometheus/ca.crt
      bearer_token_file: /etc/prometheus/token
      namespaces:
        names:
          - monitoring
```

It *seems* that this is targeting everything in the monitoring namespace, so if thats just prometheus you should be fine, but at this point we're into SD specifics of your setup which I don't have a lot of context on :) The things to keep in mind is that you want nodes with the same data in the same servergroup, and if the data is different it needs to be a separate servergroup.

**Comment by Swetad90** [comment]
This is my current deployments in monitoring namespace.
I have 2 replicas of Prometheus & I want promxy to be able to aggregate from both:

`
NAME                                         READY   STATUS    RESTARTS   AGE
pod/prometheus-deployment-697d6849d9-hpw8h   1/1     Running   0          3h6m
pod/prometheus-deployment-697d6849d9-x2f6r   1/1     Running   0          3h7m
pod/promxy-5fb965f987-p4pcx                  1/1     Running   0          65m

NAME                         TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/prometheus-service   NodePort   10.233.18.245   <none>        9090:30326/TCP   25h
service/promxy               NodePort   10.233.8.188    <none>        8082:31708/TCP   135m

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/prometheus-deployment   2/2     2            2           25h
deployment.apps/promxy                  1/1     1            1           3h5m

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/prometheus-deployment-697d6849d9   2         2         2       25h
replicaset.apps/promxy-5fb965f987                  1         1         1       65m
replicaset.apps/promxy-7db7d9c488                  0         0         0       3h5m
`

And that is why I gave those relabel_config to dynamically get the pods incase the pods restarts or gets deleted.

Do you have any sample or example for kubernetes_sd_config for promxy ?

**Comment by jacksontj** [comment]
`kubernetes_sd_configs` is what defines [what targets to talk to](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) the `relabel_config` (1) filters the results and (2) modifies the labels retrieved from discovery. From what you have described it looks like you have promxy and prometheus in the same namespace.

So from what I'm seeing (and this is likely incomplete, as I don't have access to your system and don't personally use the k8s SD in prom) you should (1) configure the `kubernetes_sd_configs` to scope the pods to the prometheus containers only (can be done either with container name, pod label, etc.) (2) remove the relabel_config as it shouldn't be necessary for promxy to discovery prometheus (and from what I'm seeing there it looks like it would actually break it-- as its replacing the address).

**Comment by Swetad90** [comment]
`

     promxy:
      server_groups:
      - kubernetes_sd_configs:
        - api_server: https://172.xx.xx.xxx:6443
          role: pod
          tls_config:
            #insecure_skip_verify: true
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          namespaces:
            names:
              - monitoring
`

I was able to run 2 pods in one namespace of prometheus and get metrics. Here are my 2 observations:
1. Promxy just aggregates over **existing** pods or prometheus instances. If we lose one pod/instance, it takes from the existing one and we lose the data of the dead pod
Tested: create 2 pods **over 15 min gap** and configure promxy. You can see data from the earliest time. delete the older pod, the older data gets deleted from grafana.

Will using persistent volume solve this? so that we don't have gaps on the graph

2. If one of the prometheus pod goes down, even ig K8s spins up another, all dashboards goes blank. THere is no datapoints shown until we reimport the dashboard. This behaviour is not consistent though, happened twice and on third time the dashboards on grafana survived the pod restart.

**Comment by jacksontj** [comment]
> Promxy just aggregates over existing pods or prometheus instances. If

If by this you mean promxy only aggregates data over live prometheus hosts you are correct. Promxy is just an aggregating proxy, not a datastore. This stitching together of data allows you to have N, lets say 2, prometheus hosts configured the same so when one restarts we can use the data from the other to fill the holes. You are correct though if they don't have the same data promxy won't have it (it only aggregates the data it has access to).

> Will using persistent volume solve this? so that we don't have gaps on the graph

Persistent volumes will mean that prometheus will keep the data across restarts; if you are running prometheus *without* persistent volumes you will definitely have lots of holes (and is likely not what you want). For that I'd suggest googling around for setting up prometheus in k8s; I know there are a lot of operators etc -- but that is all out of scope of promxy.

> If one of the prometheus pod goes down, even ig K8s spins up another, all dashboards goes blank. 

I'm not sure what you mean here by "goes blank" -- if you don't have persistent volumes you would definitely get at least holes (and maybe data missing). If you mean the dashboard disappeared that sounds like a grafana issue (possibly not using persistent volumes there either?).

**Comment by jacksontj** [comment]
@Swetad90 anything remaining on this issue? If not I'll go ahead and close it out :)

**Comment by Swetad90** [comment]
We can close it out!
Thank you!
