### ISSUE TITLE
Data/Graphs show flatlined data always the last 45-60s

### ISSUE THREAD

**Issue by geekhead** [jacksontj/promxy#190]
I've been noticing that data/graphs are flatlined for the last 45-60s worth of data but if you wait a minute and re-run the query with the exact same time window, it shows the merged results properly.  This happens regardless if my two backend VictoriaMetrics servers have all the data or not. After a minute goes by, the data values/graphs are fine. Running the query directly to a VictoriaMetrics backend doesn't show this behavior so the data is fine there. Somewhere in the Promxy path the data is getting changed before outputted or just not being retrieved properly at all, not sure yet. 

![Screen Shot 2019-07-03 at 6 50 24 PM](https://user-images.githubusercontent.com/2513533/60629495-fa989d00-9dc3-11e9-8ad1-c6f1a3a4d632.png)

And here's the debug logs for the last 5 minutes of data:
```
DEBU[2019-07-03T22:55:45Z] http://prometheus1-b:8428                     api=GetValue end="2019-07-03 22:55:46 +0000 UTC" matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" start="2019-07-03 22:50:46 +0000 UTC"
DEBU[2019-07-03T22:55:45Z] http://prometheus1-a:8428                     api=GetValue end="2019-07-03 22:55:46 +0000 UTC" matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" start="2019-07-03 22:50:46 +0000 UTC"
DEBU[2019-07-03T22:55:45Z] http://prometheus1-b:8428                     api=GetValue end="2019-07-03 22:55:46 +0000 UTC" matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" start="2019-07-03 22:45:46 +0000 UTC"
DEBU[2019-07-03T22:55:45Z] http://prometheus1-a:8428                     api=GetValue end="2019-07-03 22:55:46 +0000 UTC" matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" start="2019-07-03 22:45:46 +0000 UTC"
DEBU[2019-07-03T22:55:45Z] http://prometheus1-b:8428                     api=GetValue end="2019-07-03 22:55:46 +0000 UTC" matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" start="2019-07-03 22:50:46 +0000 UTC" took=4.776123ms
DEBU[2019-07-03T22:55:45Z] http://prometheus1-a:8428                     api=GetValue end="2019-07-03 22:55:46 +0000 UTC" matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" start="2019-07-03 22:50:46 +0000 UTC" took=11.814527ms
DEBU[2019-07-03T22:55:45Z] Select                                        matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" selectParams="&{1562194246000 1562194546000 0 }" took=12.55113ms
172.31.69.141 - - [03/Jul/2019 22:55:45] "GET /api/v1/query HTTP/1.1 200 312" 0.013484 query=netdata_system_cpu_percentage_average%7Bdimension%3D%22user%22%7D&time=1562194546
DEBU[2019-07-03T22:55:45Z] http://prometheus1-a:8428                     api=GetValue end="2019-07-03 22:55:46 +0000 UTC" matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" start="2019-07-03 22:45:46 +0000 UTC" took=11.52559ms
DEBU[2019-07-03T22:55:45Z] http://prometheus1-b:8428                     api=GetValue end="2019-07-03 22:55:46 +0000 UTC" matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" start="2019-07-03 22:45:46 +0000 UTC" took=14.420498ms
DEBU[2019-07-03T22:55:45Z] Select                                        matchers="[dimension=\"user\" __name__=\"netdata_system_cpu_percentage_average\"]" selectParams="&{1562193946000 1562194546000 1000 }" took=14.738607ms
172.31.69.141 - - [03/Jul/2019 22:55:45] "GET /api/v1/query_range HTTP/1.1 200 7613" 0.018033 query=netdata_system_cpu_percentage_average%7Bdimension%3D%22user%22%7D&start=1562194246&end=1562194546&step=1
```

Sorry, @jacksontj for the barrage of submitted issues. I like the potential for this project as we have a big use case to using it but just want to make sure it provides us the proper data since we would be depending on it for alerting and such. Thanks

**Comment by jacksontj** [comment]
@geekhead No problem with the issues, I'm glad others are finding this useful :)

TBH I've been using promxy in prod for a long time now and have never seen that behavior.

If you change the promxy config to have a single downstream do you get the same behavior? At this point I'm at a bit of a loss on how to narrow this down. Those flat lines look like promxy either (1) didn't get a result or (2) got some nans -- since the line looks like a grafana thing, not a API response.


Could you provide the API call query + response for both VM and promxy? That should shed some light on what is happening with the data.

**Comment by jacksontj** [comment]
@geekhead any luck with gathering data for this issue?

**Comment by geekhead** [comment]
@jacksontj I have not had time to grab additional data for this

**Comment by jacksontj** [comment]
@geekhead no worries, let me know when you can gather some more data-- as at this point I don't have a way to repro this issue :(

**Comment by jacksontj** [comment]
@geekhead any plans to get back to this? If not we can close it out until you have some time, at this point I'm unable to make progress on this bug report at all :cry:

**Comment by geekhead** [comment]
@jacksontj I'll have some time hopefully in the next couple of weeks. You can close it out for now and if I find any more info I'll post it in here. Thanks

**Comment by jacksontj** [comment]
Sounds like a plan :)
