### ISSUE TITLE
Alerting configuration question

### ISSUE THREAD

**Issue by jacksontj** [jacksontj/promxy#201]
Hi,
I'm trying to setup an architecture where I have 2 x (multiple Prometheis, sending metrics to victoria-metrics ) which are queried by Promxy.
This way I have federation of multiple Prometheis + long term storage + HA + alerting rules defined for a complex setup.
But the alerts generated by Prometheus are not sent the the AlertManager by Promxy, they could be queried with promql, but I have to connect all Prometheis instances to the AlertManagers.

Is that the expected way to setup?

Thanks

_Originally posted by @thosil in https://github.com/jacksontj/promxy/issues/92#issuecomment-512747006_

**Comment by jacksontj** [comment]
@thosil first off, welcome to promxy :) Generally commenting on old issues either gets lost or slow 
responses (I saw the email but couldn't find the issue :) ).

>  This way I have federation of multiple Prometheis + long term storage + HA + alerting rules defined for a complex setup.

So from what I understand you have shards of prometheus (2 nodes per shard) all sending data to VM. In this setup you can do alerting on the prometheus hosts themselves or on promxy (or both!)

> But the alerts generated by Prometheus are not sent the the AlertManager by Promxy

This entirely depends on where the alert rules are being processed. If prometheus has an alert rule it runs that alert rule against itself and sends the state to AlertManager. If promxy is executing the alerting rules it will execute the rules against its configuration (presumably all the prom hosts you have) and then report the alert state to AlertManager. All the alerts that need a global view  (e.g. need data across shards) need to run on promxy. For the rest you can either put them on promxy as well or run them on the local prometheus node. If you don't *need* data out-of-shard it is more efficient to run those alerts local to the prometheus host -- but depending on scale etc. it might not be worth the more complicated config management (which tier alerts go on).


Hopefully that answers the question?

**Comment by thosil** [comment]
Hi @jacksontj ,

crystal clear!

thanks :-)
