### ISSUE TITLE
Memory retention on queries

### ISSUE THREAD

**Issue by sajidbsk** [jacksontj/promxy#206]
It seems even after large queries are cancelled (due to for e.g context timeout), the memory consumption by promxy remains the same. If I remember correctly, no caching is implemented yet and also the memory consumption seems to be accumulative (i.e, if you repeat, memory consumption doubles). I am guessing there's a memory leak somewhere.
This is how I found the issue: 
I set the query.timeout flag to be 1m and was checking the memory by ps aux | grep promxy. It seems when the context timed out and several minutes after it times out, the memory consumption is the same.
![Screenshot from 2019-08-14 15-34-12](https://user-images.githubusercontent.com/20984263/63061300-83b5f000-bea9-11e9-8a8b-adfa7c4ec084.png)
This is what the graph looks like when we're looking at the memory usage through node exporter. (I also made sure trickster is inactive)

**Comment by sajidbsk** [comment]
Update: I ran a really intensive query that would usually timeout but I set the timeout to 50m so that it completes. This is what my memory usage looks like after the query:
![Screenshot from 2019-08-15 12-56-00](https://user-images.githubusercontent.com/20984263/63122634-12834500-bf5c-11e9-9db1-6a280501333c.png)
It seems like it's not limited to cancelled queries only

**Comment by jacksontj** [comment]
This actually has to do with how go manages memory not so much promxy (decent explanation -- https://utcc.utoronto.ca/~cks/space/blog/programming/GoNoMemoryFreeing). Since promxy is written in go we'll be somewhat limited by the options we have in the language.
