### ISSUE TITLE
Query fails with 'integer divide by zero'

### ISSUE THREAD

**Issue by toombs-caeman** [jacksontj/promxy#209]
We ran into a specific query that fails to run through promxy, but succeeds through prometheus

    min_over_time(sum by (instance)(rate(prometheus_tsdb_wal_page_flushes_total[1m]))[1h:])

I've changed the metric to something generic, so I get that the aggregation here doesn't make a lot of sense, but it exhibits the same behavior.
Promxy returns `unexpected error: runtime error: integer divide by zero` with code 422.

**Comment by jacksontj** [comment]
Thanks for the report! I was able to repro and have a fix PR opened (https://github.com/jacksontj/promxy/pull/210). It seems that the upstream test runs aren't working properly so I'll have to get those working again, but this should fix the immediate issue :)

**Comment by toombs-caeman** [comment]
Wow! Thanks for the super fast response. It works great!
