### ISSUE TITLE
Slow query response with multiple clients

### ISSUE THREAD

**Issue by arjunnath** [jacksontj/promxy#21]
The promxy proxy service seems to be considerably slower when there are multiple different clients running queries. When we had multiple end-users (3-4) open grafana dashboards with promxy as datasource, the response time dropped drastically.

From looking at the log output to stdout - it seems to run the queries one at a time (queue). This may be why the delay increases.

1 client : 2-4 second dashboard load/refresh time
3 clients : 5-30 second dashboard load/refresh time.

**Comment by jacksontj** [comment]
The only limitation I can think of is the promql max concurrency limit (which is set quite low). I can't remove it as of yet, but I do have an issue to make those configurable (#20).

Since you guys are building from source, do you mind testing out the commit on the `perf` branch

**Comment by jacksontj** [comment]
Alternatively (to avoid the rebuild and push) you could check the `prometheus_engine_queries` metric from promxy, if that is at `20` during your tests -- then its definitely the limits from #20

**Comment by jacksontj** [comment]
I just merged #24 so this option is now (1) a higher default and (2) CLI configurable.

**Comment by jacksontj** [comment]
I wanted to check in on this issue. There was another similar issue (#22) which reminded me that the JSON marshal perf is really slow in prometheus <2.2. Promxy has an option to enable `remote_read` to bypass that slowness (if upgrading prometheus is not doable)

**Comment by arjunnath** [comment]
Can you elaborate some more on the remote_read option ?
How does that help with the slowness issue ?

**Comment by jacksontj** [comment]
Are you still still experiencing this issue?

**Comment by arjunnath** [comment]
No, we have not seen the issue since we upgraded both promxy and Prometheus.

**Comment by jacksontj** [comment]
Glad to hear it! I'll go ahead and close out this issue, feel free to re-open or create a new issue if the problem resurfaces.
