### ISSUE TITLE
On ServerGroup usage

### ISSUE THREAD

**Issue by 548017** [jacksontj/promxy#225]
I'm running on k8s, and I have several (50-100) projects, each one has its own prometheus (some projects have two Prometheus for HA). And I want to have a global view. Question is: Can I use k8s service discovery mechanism so all projects are under the same ServerGroup? What are the differences between using one ServerGroup per project and one "_global_" ServerGroup?
Is there any point after one approach or the other will present challenges regards scalability or performance?

**Comment by jacksontj** [comment]
> Can I use k8s service discovery mechanism so all projects are under the same ServerGroup?

Promxy does support using k8s service discovery, so it is definitely possible to discover the endpoints/targets through k8s service discovery.

> What are the differences between using one ServerGroup per project and one "global" ServerGroup?

This is covered in the [README](https://github.com/jacksontj/promxy#what-is-a-servergroup) -- TLDR; everything in a "server group" is considered the same data. In practice you can think about this as "if it has the same scrape config, it is in the same server group". So in the example you have described if you have 100 prometheus hosts all with unique scrape configs that would be 100 server groups.

> What are the differences between using one ServerGroup per project and one "global" ServerGroup?

If the data is unique across the different projects (which presumably it is) configuring them all as one global server group would result in incorrect responses (as a response from 1 would be considered "complete").

**Comment by 548017** [comment]
Thanks for your answer @jacksontj 
One additional question: is it possible to set up SD for ServerGroups or are they statically defined? What I mean is, if I add an additional project, is there some way to have the ServerGroup automatically added to configuration or the only way is to manually define the new ServerGroup (for which I can configure the underlying Prometheus with SD) ?

**Comment by jacksontj** [comment]
Short answer: yes

Longer-answer: yes, but its complicated :) Basically this can be accomplished using [relabel configs](https://github.com/jacksontj/promxy/blob/master/pkg/servergroup/config.go#L80) on the servergroup. The way the combination of data is done is actually uniqueness of the labels associated with the servergroup/target. So you could (for example) add a relabel_config like:


```
      relabel_configs:
        - source_labels: ['__meta_kubernetes_node_annotation_service_name']
          target_label: '_service_name'
```

Which should get you the desired behavior (assuming `__meta_kubernetes_node_annotation_service_name` is the name of the project/service). This has the added benefit of letting you target queries using this label (if you have a query with `_service_name` it'll only send it to the prometheus downstreams that have that service on it).

**Comment by jacksontj** [comment]
I'm going to assume the question is answered due to lack of response, if it isn't feel free to re-open :)
