### ISSUE TITLE
glog causes crash after a while if it cannot write to /tmp

### ISSUE THREAD

**Issue by vsliouniaev** [jacksontj/promxy#237]
Looks like this has been fixed by switching to go modules and glog-gokit https://github.com/prometheus/prometheus/pull/4931 in the main prometheus codebase.

Actual log from crash is:
```
log: exiting because of error: log: cannot create log: open /tmp/promxy.promxy-5f9f69bbc8-mvbhl.unknownuser.log.WARNING.20191112-060148.1: no such file or directory
```

**Comment by jacksontj** [comment]
#239 has the fix, and I created a release with this as well: https://github.com/jacksontj/promxy/releases/tag/v0.0.55
