### ISSUE TITLE
Query with <aggr>_over_time, sum and rate returns empty output

### ISSUE THREAD

**Issue by yashumitsu** [jacksontj/promxy#245]
Hello!

This query returns empty result via promxy:
`max_over_time(sum by(instance) (rate(node_cpu_seconds_total[1m]))[1h:])`

But the Prometheus response is fine:
* http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=max_over_time(sum%20by(instance)%20(rate(node_cpu_seconds_total%5B1m%5D))%5B1h%3A%5D)&g0.tab=1

Version: v0.0.55

_/etc/promxy/config.yaml_:
```
promxy:
  server_groups:
    - static_configs:
      - targets:
        - demo.robustperception.io:9090
```

_debug log_:
```
Nov 19 11:50:55 localhost.localdomain promxy[24029]: time="2019-11-19T11:50:55Z" level=debug msg="AggregateExpr sum by(instance) (rate(node_cpu_seconds_total[1m]))"
Nov 19 11:50:55 localhost.localdomain promxy[24029]: time="2019-11-19T11:50:55Z" level=debug msg="http://demo.robustperception.io:9090" api=Query query="sum by(instance) (rate(node_cpu_seconds_total[1m]))" ts="2019-11-19 11:50:55.273 +0000 UTC"
Nov 19 11:50:55 localhost.localdomain promxy[24029]: time="2019-11-19T11:50:55Z" level=debug msg="http://demo.robustperception.io:9090" api=Query query="sum by(instance) (rate(node_cpu_seconds_total[1m]))" took=63.180447ms ts="2019-11-19 11:50:55.273 +0000 UTC"
Nov 19 11:50:55 localhost.localdomain promxy[24029]: 10.0.2.2 - - [19/Nov/2019 11:50:55] "GET /api/v1/query HTTP/1.1 200 87" 0.064316 query=max_over_time%28sum+by%28instance%29+%28rate%28node_cpu_seconds_total%5B1m%5D%29%29%5B1h%3A%5D%29&time=1574164255.273&_=1574164250864
```

I know the promxy performs black magic dealing with aggregation functions. I would like to ask your opinion. This query is valid or it should be simplified?

**Comment by jacksontj** [comment]
@yashumitsu This was a very interesting problem, I've been working on it off and on for the last few days. So apparently Subquerys are very *very* special inside of promql. Basically they are a matrix of data that isn't a matrixselector -- so that wasn't working with all the NodeReplacer in the prom fork promxy was using. So I have since updated the fork and added support and the feature is in #246
