### ISSUE TITLE
Are multiple servers of different data supported?

### ISSUE THREAD

**Issue by barnettZQG** [jacksontj/promxy#249]
In addition to high availability, the stand-alone capacity of Prometheus is also a problem.

If I have 1000 nodes to be monitored, a single Prometheus can only handle 500 of them, then we need multiple Prometheus to form the data partition mode, of course, each partition can have 2 Prometheus.

I wonder if there is a query agent that can screen the data of the bottom Prometheus and provide a unique query entry.

This is a similar project:
https://github.com/cortexproject/cortex

**Comment by jacksontj** [comment]
Thanks for the question! Promxy was initially made to cover this case (more detail [here](https://github.com/jacksontj/promxy#why-promxy)). For your example, if you simply have 2 prometheus hosts each scraping 500 nodes you can configure them as 2 different [servergroups](https://github.com/jacksontj/promxy#what-is-a-servergroup) in promxy and they will be aggregated together.

Cortex is a different approach, promxy simply aggregates promql endpoints -- cortex is intended as a shared long-term storage (integration through remote_storage).

**Comment by jacksontj** [comment]
Hopefully my response was sufficient, if you have any further questions feel free to re-open.
