### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by sundy-li** [jacksontj/promxy#256]
I noticed that `promxy` still use the vendor to track third libs, maybe we should enable go module.

**Comment by jacksontj** [comment]
To clarify for anyone wanting to track this, I'm okay swapping from dep -> go mod -- but I still want a vendor directory in the repo (more than once an upstream has messed up a repo causing me headache, especially given the large number of deps for this project).

**Comment by valyala** [comment]
FYI, VictoriaMetrics uses `go mod` with `vendor` directory for the same reasons. It passes `-mod=vendor` to `go build` and uses `go mod tidy && go mod vendor` for updating `vendor` directory - see [vendor-update](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/aeea59e2800fc0c41be6723f5f7d6fc7db4c9553/Makefile#L101) Makefile rule and other build rules in the [Makefile](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/aeea59e2800fc0c41be6723f5f7d6fc7db4c9553/Makefile)

**Comment by Wing924** [comment]
any updates?

**Comment by jacksontj** [comment]
@zeeshen has contributed a PR to do the swap over (#308) so this is done :tada:
