### ISSUE TITLE
Promxy returns no datapoint from VictoriaMetrics instance.

### ISSUE THREAD

**Issue by ryotarai** [jacksontj/promxy#263]
Promxy returns no datapoint when a target of a server group is VictoriaMetrics instance. This may be due to VictoriaMetrics' `-search.latencyOffset`.

from VictoriaMetrics help:
>   -search.latencyOffset duration
>        The time when data points become visible in query results after the colection. Too small value can result in incomplete last points for query results (default 30s)

Enabling lookback in Promxy resolves this issue:

```diff
--- a/pkg/proxystorage/proxy.go
+++ b/pkg/proxystorage/proxy.go
@@ -359,7 +359,7 @@ func (p *ProxyStorage) NodeReplacer(ctx context.Context, s *promql.EvalStmt, nod
                                series[i] = &proxyquerier.Series{iterator}
                        }

-                       ret := &promql.VectorSelector{Offset: offset, DisableLookback: true}
+                       ret := &promql.VectorSelector{Offset: offset}
                        ret.SetSeries(series, promhttputil.WarningsConvert(warnings))

                        // Replace with sum(count_values()) BY (label)
@@ -393,7 +393,7 @@ func (p *ProxyStorage) NodeReplacer(ctx context.Context, s *promql.EvalStmt, nod
                                series[i] = &proxyquerier.Series{iterator}
                        }

-                       ret := &promql.VectorSelector{Offset: offset, DisableLookback: true}
+                       ret := &promql.VectorSelector{Offset: offset}
                        ret.SetSeries(series, promhttputil.WarningsConvert(warnings))
                        n.Expr = ret

@@ -429,7 +429,7 @@ func (p *ProxyStorage) NodeReplacer(ctx context.Context, s *promql.EvalStmt, nod
                        series[i] = &proxyquerier.Series{iterator}
                }

-               ret := &promql.VectorSelector{Offset: offset, DisableLookback: true}
+               ret := &promql.VectorSelector{Offset: offset}
                ret.SetSeries(series, promhttputil.WarningsConvert(warnings))

                // the "scalar()" function is a bit tricky. It can return a scalar or a vector.
@@ -475,7 +475,6 @@ func (p *ProxyStorage) NodeReplacer(ctx context.Context, s *promql.EvalStmt, nod
                }
                n.Offset = offset
                n.SetSeries(series, promhttputil.WarningsConvert(warnings))
-               n.DisableLookback = true

        // If we hit this someone is asking for a matrix directly, if so then we don't
        // have anyway to ask for less-- since this is exactly what they are asking for
```

I found this issue in Promxy 1d6a6d848b6cb8a27d1198783e4491c5c9b1ac92 .

**Comment by jacksontj** [comment]
My guess would be that this is related to the internal caching within VM. There is a comment trying to cover this in the config (https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L52) -- if it is this caching issue adding a `nocache` query param should resolve it.

The Lookback was disabled for these queries as it isn't necessary (meaning before it would just take the most recent point we got back anyways) -- so this is likely an issue with how VM is responding.

**Comment by jacksontj** [comment]
That feature definitely sounds like the issue, i imagine that feature was put in place due to the internal caching VM does (since it would cache the result without all the most recent data). So maybe some combination of a shorter latencyOffset + disabling caching (https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L52) might work?

Also, since the report is "returns no datapoint" I'm assuming this is an instant query? If this was for a range query I'd be suspicious since I could see this latencyOffset messing with the most recent points (last 30s) but not minutes or hours back.

**Comment by jacksontj** [comment]
Haven't heard back in a bit so I'm going to close this out. If this is still an issue please feel free to re-open so we can pick it back up :)
