### ISSUE TITLE
Question: HA Promxy? - Architecture feedback

### ISSUE THREAD

**Issue by slikk66** [jacksontj/promxy#270]
Hello! The readme says general questions are OK here :)

I put together a proposed architecture for an HA monitoring/alerting system to monitor 3+ K8s clusters (EKS) using VictoriaMetrics and Promxy.

Is it possible to run 2 promxy nodes behind a load balancer?  The docs don't seem to mention this, not sure if is fine or if it negates the whole purpose of promxy.  If possible, I'd like to have 2 nodes.

Basically, I'm thinking to run the Docker deployment for VictoriaMetrics which includes:
 -prometheus
 -grafana
 -victoriametrics
and adding to that deploy
 -promxy
 -alertmanager

Which would give us HA on all services.  They'd have to criss-cross a bit on some of the services pointing back and forth to the other node using internal DNS.

Here's the full post on reddit, if anyone has comments or feedback that would be appreciated.

https://www.reddit.com/r/VictoriaMetrics/comments/f6mby9/jumping_in_looking_for_feedback_on_architecture/

here's a high level infra arch diagram: https://imgur.com/a/U4lRRBz

Thanks!!

**Comment by jacksontj** [comment]
> Is it possible to run 2 promxy nodes behind a load balancer? The docs don't seem to mention this, not sure if is fine or if it negates the whole purpose of promxy. If possible, I'd like to have 2 nodes.

Yes this is completely possible/doable and exactly what I do :) You can also have layers of promxy if you want those intermediate layers of aggregation (I've seen this for regional vs global aggregation in large multi-AZ/region builds).

But as far as promxy is concerned it can have any downstream prometheus API you want. So you could even have promxy aggregate both VM and prometheus (if you use the time offset configuration for the SGs).

**Comment by jacksontj** [comment]
Hopefully the above answer was sufficient :) If not feel free to re-open.
