### ISSUE TITLE
Question: Is there a guide for step by step setup of Promxy?

### ISSUE THREAD

**Issue by dm9bbadd4** [jacksontj/promxy#271]
Apologies for the noobness of the question but i am very noob to Prometheus and, by extension, Promxy. I read through all the docs, looked through the config, and i still can't figure out how to integrate this with my multiple Prometheus installs. 

I have three prometheus installs on AWS EC2 instances all in three separate regions. They are monitoring other EC2 instances via service discovery. Each instance has node exporter installed to it. On one prometheus instance i have blackbox exporter monitoring endpoints and alertmanager running for blackbox. The other two prom instances just have node exporter. 

A few questions i have are: 
- Do i have to install this on each instance that has Prometheus?
- How do i get grafana to point to Promxy?
- Do all my Prometheus instances come under the same server group or does each one need it's own?

Any help is much appreciated.

**Comment by dm9bbadd4** [comment]
Also when running Promxy, it just says Promxy is starting and nothing else. Is this expected behavior? I saw it listens on port 8083, do i point other Promxy installs to that ip:port or directly to other Prometheus ip:ports?

**Comment by jacksontj** [comment]
No worries about the questions, docs are definitely still a weak point on this project -- so feel free to ask :)

> Do i have to install this on each instance that has Prometheus?

No, Promxy is an aggregating proxy -- and as such it can sit anywhere else as long as it can talk to all the downstream prometheus APIs you want to aggregate. Usually this is on separate hosts from the prometheus hosts (although you don't have to separate them)

> How do i get grafana to point to Promxy?

This is actually a lot easier than it sounds, you'd just add promxy as a "prometheus" datasource in grafana. So you'd add it the same was as a prometheus source -- just use the correct ports

> Do all my Prometheus instances come under the same server group or does each one need it's own?

A [servergroup](https://github.com/jacksontj/promxy#what-is-a-servergroup) is a set of hosts that have the same data on them; so based on what you described (3 separate regions scraping 3 separate things) I'd expect you need to have them be 3 separate servergroups. One thing to watch out for when setting it up -- you might need to include `labels` in each servergroup to avoid some aggregation issues (more details https://github.com/jacksontj/promxy/issues/260#issuecomment-587975870 if interested).

> Also when running Promxy, it just says Promxy is starting and nothing else. Is this expected behavior?

This is expected; higher log levels will say more, but the default just logs the start.

> I saw it listens on port 8083, do i point other Promxy installs to that ip:port or directly to other Prometheus ip:ports?

You can point promxy to other promxys if you want intermediate layers of aggregation (although from your setup it sounds like that isn't desired). So you'd presumably configure promxy with 3 servergroups each with a label defining which region and each pointing to the 1 prometheus host in that region. Then you should be able to add the promxy host as a prometheus endpoint in grafana and have aggregation working. Another thing that might be of interest, you could consider running 2 prometheus hosts per region if you wanted data redundancy (definitely not required, just something that might be of interest -- covered somewhat in the [MOTIVATON](https://github.com/jacksontj/promxy/blob/master/MOTIVATION.md) doc).

**Comment by dm9bbadd4** [comment]
Thank you so much for this information, very helpful stuff. Sorry i haven't replied in a while, i was off work for a week. Today I'm going to try out what you said and will let you know if i'm successful.

**Comment by dm9bbadd4** [comment]
So i have Promxy pointing at my three Prom instances but i can't access the Promxy http endpoint, and neither can Grafana. Port 8083 is open, and Promxy is giving me no errors, and turning on debug logging to stdout it's able to update the targets i've given it, 

Any clue as to what i'm doing wrong? Thanks.

**Comment by dm9bbadd4** [comment]
So i got the endpoint working (leaving Promxy to use it's default port of 8082) but it's not seeing my prometheus targets.

![Annotation 2020-03-02 153834](https://user-images.githubusercontent.com/58006995/75691235-e501ad00-5c9b-11ea-8098-e5d5968c3e47.png)
This is on the Promxy web interface, you can see it's displaying no targets despite my config having 3 server groups. I read in your readme that i don't need to configure my Prometheus instances around Promxy but do i need to add Prometheus type settings to the Promxy config? Like service discovery for example?

**Comment by dm9bbadd4** [comment]
Just read commit #32 . Looking in Grafana, it seems everything is working (except for this one dashboard not able to read node exporter metrics dynamically). Sorry for all the posts. Thanks for all the help.
