### ISSUE TITLE
Promxy and Alertmanager - Unable to Trigger Alerts   

### ISSUE THREAD

**Issue by Yu6936** [jacksontj/promxy#281]
Hi,

    I am having issues with triggering alerts from Promxy to Alertmanager.   I have read through issue #250 but still unable to resolve my problem.  We have 2 Victoriametrics VM feeding to Promxy and I will like to setup alerting rules on Promxy to be forwarded to Alertmanager.  I was able to successful generate the "Watchdog rule" reference in issue #250 but not any of my own custom rules are triggering.  Would you have any ideas where I should be digging for clues?  Any help would be greatly appreciated.   Thanks!   

![Screen Shot 2020-03-09 at 2 01 40 PM](https://user-images.githubusercontent.com/32713607/76257262-9b224500-620e-11ea-81db-2af03b5ff6db.png)

[config.yaml.txt](https://github.com/jacksontj/promxy/files/4308893/config.yaml.txt)

**Comment by jacksontj** [comment]
I know of a few users (including myself) that use alerting with promxy, so definitely odd that you are seeing this behavior. You could look into higher log levels (as the rule engine does log a LOT about what it does in debug). I'd also suggest trying the same query in the `graph` section to see if promxy is reading from VM properly for regular graphing (if its erroring or not returning values then it wouldn't trip).

**Comment by Yu6936** [comment]
I'll keep looking with the debug option ON but still unsuccessful. I'm going to play around with the alerting rules more to see if I get anywhere.

**Comment by Yu6936** [comment]
Ok, I've found the issue in my config.yaml file and alerts are firing.  I needed to add:

query_params:
        nocache: 1

Thanks!
