### ISSUE TITLE
count_values not returning correct labels when using `by` clause

### ISSUE THREAD

**Issue by matejzero** [jacksontj/promxy#283]
Hello,

I hope my title is correct for the problem I'm seeing.

I'm monitoring OpenVPN server and this is part of the query I'm using to count the number of times a user has connected in the last 24h:
```
count_values("connection_time", 
  count_over_time(openvpn_server_client_received_bytes_total{common_name!="UNDEF"}[1d])
) by (common_name)
```

Prometheus and VictoriaMetrics return the following:
```
{common_name="user1",connection_time="6"} 1
{common_name="user2",connection_time="30"} 1
{common_name="user3",connection_time="720"} 1
```

But Promxy returns:
```
{connection_time="6"} 50
{connection_time="30"}  1
{connection_time="720"} 1
```

I get the same output with Prometheus if I remove the `by (common_name)` from the query.

I'm running Promxy v0.0.57.

**Comment by jacksontj** [comment]
Thanks for the report! I was able to reproduce this and have a fix PR open at #284
