### ISSUE TITLE
No docker image in README

### ISSUE THREAD

**Issue by allen13** [jacksontj/promxy#286]
I saw this referenced in another issue https://github.com/jacksontj/promxy/issues/187  saying it was in the README.md but I don't see it. Could this be added to the README and perhaps in release notes as well? https://quay.io/repository/jacksontj/promxy Thanks!

**Comment by jacksontj** [comment]
Welcome! 

![Screenshot from 2020-03-17 22-02-41](https://user-images.githubusercontent.com/1619869/76926984-0ae1a100-689b-11ea-99bb-ab8e9d77e7ac.png)

This button on the README links to it, and you can also find example k8s configuration (including the registry link) [here](https://github.com/jacksontj/promxy/blob/master/deploy/k8s/promxy.yaml).

**Comment by allen13** [comment]
Thank you! Totally missed that!
