### ISSUE TITLE
Promxy v0.0.58 panic with PromQL subqueries and range vectors

### ISSUE THREAD

**Issue by geekhead** [jacksontj/promxy#291]
We have a couple Grafana dashboards for Kubernetes that uses PromQL subqueries and range vectors that work fine when sent directly to a Victoriametrics or Prometheus backend but causes Promxy to crash and panic. We are currently running version `0.0.58`

### This query causes Promxy to panic and crash
```
avg_over_time(avg(container_memory_usage_bytes{pod_name=~"autojob-peraccount-primary.*",container!="POD"})[1m:]) / avg_over_time(avg(kube_pod_container_resource_requests_memory_bytes{pod=~"autojob-peraccount-primary.*",container!="POD"})[1m:])
```

**Traceback**
```
panic: Unhandled SubqueryExpr return type: *promql.BinaryExpr

goroutine 2479 [running]:
github.com/jacksontj/promxy/pkg/proxystorage.(*ProxyStorage).NodeReplacer(0xc000277920, 0x2734240, 0xc000e20700, 0xc000b5e690, 0x26dd9e0, 0xc000db3950, 0xc0009430e0, 0x0, 0xc000e20700, 0xc001000000)
	/go/src/github.com/jacksontj/promxy/pkg/proxystorage/proxy.go:262 +0x31f2
github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.Walk(0x2734240, 0xc000e20700, 0x26e0040, 0xc000e20600, 0xc000b5e690, 0x26dd9e0, 0xc000db3950, 0xc000e207c0, 0x3, 0x4, ...)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/ast.go:275 +0x186f
github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.Walk(0x2734240, 0xc000e20700, 0x26e0040, 0xc000e20600, 0xc000b5e690, 0x26e0020, 0xc00100b4c0, 0xc000e207c0, 0x3, 0x4, ...)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/ast.go:300 +0x430
github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.Walk(0x2734240, 0xc000e20700, 0x26e0040, 0xc000e20600, 0xc000b5e690, 0x26dd900, 0xc000db1f60, 0xc00100b4a0, 0x2, 0x2, ...)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/ast.go:355 +0x1518
github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.Walk.func2(0x2734240, 0xc000e20700, 0x26e0040, 0xc000e20600, 0xc000b5e690, 0xc000cb86c0, 0xc000277a60, 0xc00100cfc0, 0xc001020480, 0x1, ...)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/ast.go:335 +0xf1
created by github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.Walk
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/ast.go:334 +0xe1f
```

### This query returns an internal server error with a 500 status code
```
avg_over_time(avg(container_memory_usage_bytes{pod_name=~"autojob-peraccount-primary.*",container!="POD"})[1m:])
```

**Output:**
```
ip.ip.ip.ip - - [26/Mar/2020 14:32:31] "GET /api/v1/query_range HTTP/1.1 500 6016" 0.000573 query=avg_over_time%28avg%28container_memory_usage_bytes%7Bpod_name%3D~%22autojob-peraccount-primary.%2A%22%2Ccontainer%21%3D%22POD%22%7D%29%5B1m%3A%5D%29&start=1585229550&end=1585233150&step=10
```

**Comment by jacksontj** [comment]
Thanks for the report! This is actually related to #273 -- short version the way subqueries are implemented currently isn't complete -- so there are some edge-cases where there are panics or missing data. I have a PR open with some fixes, but they are incomplete as well. This just needs some more TLC to finish up a fix for -- but its been a crazy time (and I'm sure it is for everyone). So I'll get back to this once I can -- and if anyone else wants to pick it up PRs are always welcome :)

**Comment by geekhead** [comment]
@jacksontj Thanks for getting back and take care of you and your family first during this crazy time. Let me know if you need any additional info from my side of things.

**Comment by geekhead** [comment]
@jacksontj Just following up on this to see if any progress has been made. Thanks!

**Comment by jacksontj** [comment]
Unfortunately not yet, this will likely take a few days of dev time to sort out (as the current execution model doesn't do the recursion how it needs to be). Still here in the bug list, so I should get around to it eventually when some time frees up, but as always PRs are welcome :)

**Comment by geekhead** [comment]
Any word on if this bug will be addressed? Thanks

**Comment by jacksontj** [comment]
This ended up being a bit more of a hassle to fix (as probably obvious from the lack of fix). This subquery stuff has been rewritten in the promql engine in newer versions of prometheus. I'm in progress on upgrading (https://github.com/jacksontj/promxy/pull/378) and it _seems_ that this issue is gone in the newer versions (they made subqueries just convert to MatrixSelectors under the hood; so much easier all around). So once that is merged in we can revisit this issue (as it may just "get fixed" :) ).

**Comment by jacksontj** [comment]
@geekhead this issue _should_ be resolved with the prom dep update (https://github.com/jacksontj/promxy/releases/tag/v0.0.63) -- mind giving that a spin?

**Comment by jacksontj** [comment]
After the recent updates I am no longer able to reproduce this error, so I'm going to close this out. If you are able to still repro please feel free to re-open :)
