### ISSUE TITLE
Cannot read property 'status' undefined ,  when configuring promxy as datasource in grafana

### ISSUE THREAD

**Issue by vvutharkar** [jacksontj/promxy#292]
![image](https://user-images.githubusercontent.com/1565518/77712047-e15a0100-6f8f-11ea-88e2-b2ee0af5225a.png)

I have configured promxy behind a **haproxy** with the routing path /myservice . Port 443 of my haproxy redirects to the backend promxy port 8082.

The reason I put it behind haproxy is because I have two promxy instances in two data centers for redundancy. And the haproxy round robin load balances across these two. 
  
And when starting up promxy I specify the flag 
     "--web.external-url=http://something.io/myservice" 

I can access the promxy perfectly fine via my HaProxy url :  https://something.io/myservice 
And  https://something.io/myservice/status also returns the status page properly. 
https://something.io/myservice/graph loads up properly and I can run queries etc fine. 

Except when configuring the datasource on grafana and I provide "https://something.io/myservice" as the url and access as 'Browser' , and test the datasource, it throws the error shown in screenshot. What am I missing?

**Comment by jacksontj** [comment]
Thanks for reaching out! From the error there it seems that there was some HTTP error with the setup. If you open up developer tools in the browser you can get the response code and body which should help to shed some light on the error. The error is just saying that it can't find a `status` property in the body (which is undefined) -- so likely some error response code.

**Comment by jacksontj** [comment]
I'm going to close this out as its been a while with no update. If you are still seeing this issue please feel free to re-open :)
