### ISSUE TITLE
promxy aggregate data not collect

### ISSUE THREAD

**Issue by ly123-liu** [jacksontj/promxy#293]
we run 2 prometheus to scape metrics(use hashmod), each one scrap its metrics, and one promexy to aggregate two prometheus for view,  i found this weird things:

blew is two query, the first one is expect to sum the whole data ,but actuall returns just one data, why? anyone can explain this? thanks！！

![image](https://user-images.githubusercontent.com/57338370/78328808-a6208900-75b2-11ea-87b8-d16ddaf9bab7.png)

I checked the prometheus data and foun this data was scraped by two prometheus, port 10214 was scrap by prometheus-slave-0 , port 10213 was scrap by prometheus-slave-1 , promxy cannot aggregate two prometheus data ??

![image](https://user-images.githubusercontent.com/57338370/78329254-c56be600-75b3-11ea-9af1-b2c148b71796.png)

![image](https://user-images.githubusercontent.com/57338370/78329181-95244780-75b3-11ea-91cc-537dceb37bae.png)

**Comment by ly123-liu** [comment]
my promxy config：

global:
  evaluation_interval: 30s
  external_labels:
    source: promxy


rule_files:
  - "/etc/prometheus/alert-rule.yml"

promxy:
  server_groups:
    - static_configs:
        - targets:
          - 'prometheus-slave-0:9090'
          - 'prometheus-slave-1:9090'
      remote_read: false
      query_params:
        nocache: 1
      http_client:
        dial_timeout: 30s

**Comment by jacksontj** [comment]
Thanks for reaching out! From the description above it sounds like you have configured the 2 prometheus hosts to scrape different targets. In the promxy configuration pasted above it seems that both prometheus hosts are in the same servergroup (they'll need a label to differentiate as well -- https://github.com/jacksontj/promxy/issues/260#issuecomment-587975870). So as configured today promxy is treating the 2 prometheus hosts as if they  have the same data -- which based on your initial post sounds incorrect. Once you split those with labels promxy will treat them as unique datasources and you should start seeing both sets of data.

**Comment by jacksontj** [comment]
I'm going to close this out as its been a while with no update. If you are still seeing this issue please feel free to re-open :)
