### ISSUE TITLE
No any settings and logging for remote write

### ISSUE THREAD

**Issue by wf1nder** [jacksontj/promxy#295]
We using promxy to balance user requests from Grafana into HA-pair of VictoriaMetrics clusters. Also it is used for executing recording rules, which it pushes back into VM by remote_write.

Today we are faced with some problems, presumably this is networking issues, when there appeared gaps in graphs which makes by recording rules. Looks like promxy can't push it into VM randomly some times.

Debug was complicated because of two things:

  - promxy do not write anything to log about remote_write operation: no connection errors, no timeout, etc. During some investigations I accindently specified wrong port of endpoint in promxy config file in remote_write section, and even in this case promxy didn't write any error to log. promxy was started with ```--log-level=debug``` option.

  - there are no any settings in promxy_write configuration: can't specify request timeout, number of retries.

Is there any chance to get remote write logging and some settings in any upcoming releases?

Thanks.

**Comment by jacksontj** [comment]
First off, thanks for reaching out! 

So first off; logging does seem to be missing -- I just added it in #296

Second, the remote_write configuration is the same as upstream prometheus (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) so you can specify a lot of options there (including timeout).

**Comment by wf1nder** [comment]
I supposed that everything about configuring remote_write is similar to prometheus, but without logs it was difficult to check. The example config file [contains so few description about remote_write](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L22-L26), and this was confusing.

Thank you!

**Comment by wf1nder** [comment]
I builded promxy with this PR, now logs present.
But looks like something with log levels: there are records with ```fields.level=debug``` while promxy started with default log level.

**Comment by wf1nder** [comment]
Today I again catching problems with the graphs by recording rules:

![image](https://user-images.githubusercontent.com/4486762/79557104-aa689e00-80aa-11ea-87af-0a5770fba8c5.png)
I'm getting the following messages in the promxy log:

```
INFO[2020-04-17T12:44:46+03:00]                                               desiredShards=0.04454708010427206 fields.level=debug fields.msg=QueueManager.caclulateDesiredShards queue="0:http://<vm_host>:8480/insert/0/prometheus" samplesIn=1318.6417156990715 sample
sOut=1286.541795669148 samplesPending=32.099920029923396
INFO[2020-04-17T12:44:46+03:00]                                               desiredShards=0.04454708010427206 fields.level=debug fields.msg=QueueManager.updateShardsLoop lowerBound=0.7 queue="0:http://<vm_host>:8480/insert/0/prometheus" upperBound=1.3
INFO[2020-04-17T12:44:48+03:00]                                               fields.level=warn fields.msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed." queue="0:http://<vm_host>:8480/insert/0/prometheu
s"
INFO[2020-04-17T12:44:56+03:00]                                               desiredShards=0.04581358425124543 fields.level=debug fields.msg=QueueManager.caclulateDesiredShards queue="0:http://<vm_host>:8480/insert/0/prometheus" samplesIn=1227.973372559257 samples
Out=1151.3734365353184 samplesPending=76.59993602393865
INFO[2020-04-17T12:44:56+03:00]                                               desiredShards=0.04581358425124543 fields.level=debug fields.msg=QueueManager.updateShardsLoop lowerBound=0.7 queue="0:http://<vm_host>:8480/insert/0/prometheus" upperBound=1.3
INFO[2020-04-17T12:44:59+03:00]                                               fields.level=warn fields.msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed." queue="0:http://<vm_host>:8480/insert/0/prometheu
s"
INFO[2020-04-17T12:45:06+03:00]                                               desiredShards=0.050462842051578125 fields.level=debug fields.msg=QueueManager.caclulateDesiredShards queue="0:http://<vm_host>:8480/insert/0/prometheus" samplesIn=1373.1586980474058 sampl
esOut=1055.8387492282548 samplesPending=317.319948819151
INFO[2020-04-17T12:45:06+03:00]                                               desiredShards=0.050462842051578125 fields.level=debug fields.msg=QueueManager.updateShardsLoop lowerBound=0.7 queue="0:http://<vm_host>:8480/insert/0/prometheus" upperBound=1.3
INFO[2020-04-17T12:45:07+03:00]                                               fields.level=warn fields.msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed." queue="0:http://<vm_host>:8480/insert/0/prometheu
s"
```

I tried to tune up with ```max_samples_per_send```, ```max_shards``` options in both directions - to increase and decrease, but it didn't seem to have any effect. ```lowerBound``` and ```upperBound``` in the log still have the same values.

The receive endpoint seems to have no any problems and does not experience a high load. In the same time it receives several thousand times more data from prometheus cluster, and those metrics have no gaps.

Previously I tuned ```max_samples_per_send``` and ```max_shards``` options on prometheus, because it sends into VictoriaMetrics millions of time-series, and it hepled. But it looks as if promxy ignores those settings.

**Comment by wf1nder** [comment]
I'm sorry, but you just ignored what I wrote above? At least logs are always in debug mode. I don't think that it is correct behavior.

**Comment by jacksontj** [comment]
My apologies on that (I use comments in commits to link issues, and they do auto-close :) ). The log-level mismatch is definitely unexpected (as I use the same wrapper elsewhere without issues AFAIK). In addition those other tunable options should impact the send rate as they are passed to the underlying storage client (sounds like thats not what you are seeing though?)

**Comment by wf1nder** [comment]
Yes, looks like those options just ignored by promxy.
I guess that's because promxy uses old version of storage client, which have no those options yet.

**Comment by jacksontj** [comment]
Although promxy does use an older version of the storage library (because upstream broke it for external use), those options seem to be in-use (example: https://github.com/jacksontj/promxy/blob/742796bc551e3507ddb780735323e3abc2008c2d/pkg/remote/queue_manager.go#L509). So it'll require some debugging to figure out why they aren't being effective (or if maybe those options just aren't getting set high enough?)

**Comment by jacksontj** [comment]
The config options apparently worked for https://github.com/jacksontj/promxy/issues/307 :/ so not sure whats up there. For the logging though it seems this is an upstream go-kit issue (https://github.com/go-kit/kit/pull/962/files) where until recently it just logged everything as info (so there we go), just need an update of that dep to latest master and we should be set.

**Comment by wf1nder** [comment]
I tried many different values of the `max_samples_per_send` and `max_shards`, from very low to very high, and seen no any changes. We have prometheus, which pushing data to same VictoriaMetrics cluster, in which we tuned those options too, so I tried use them, but there was no any changes too. Although prometheus pushing several orders of magnitude more data, and without any data loss.

Anyway, we already wrote own separate recording rules executing application and now using it, so the priority of this problem has been lowered :/

But it would be good to fix logs.

**Comment by jacksontj** [comment]
For the logging though it seems this is an upstream go-kit issue where they always override the log level. Unfortunately even newer versions (https://github.com/go-kit/kit/pull/962/files) just let you pick *which* log level :/ so looks like we'll need an update there.
