### ISSUE TITLE
remote storage queue full for remote_write_exporter

### ISSUE THREAD

**Issue by sagor999** [jacksontj/promxy#307]
Hi,
I am a bit confused by this warning from promxy:
```Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed." queue="0:http://localhost:8083/receive"```

remote_write_exporter is running like so:
```
        args:
          - "--metric-ttl=1m"
          - "--bind-addr=:8083"
          - "--write-path=/receive"
          - "--write-text-path=/receive_text"
          - "--metrics-path=/metrics"
        command: ["/bin/remote_write_exporter"]
```

Promxy configured like so:
```
remote_write:
  - url: http://localhost:8083/receive
```

Any idea how to fix that warning? 

Thank you!

**Comment by jacksontj** [comment]
Those warnings are actually the promxy side of things warning that it can't send them fast enough -- so these *should* be tunable using the regular remote write tuning options (https://prometheus.io/docs/practices/remote_write/)

**Comment by sagor999** [comment]
Thank you!
Tweaked those and it no longer complaints.
