### ISSUE TITLE
`DisableCompression` in http transport causing API slow

### ISSUE THREAD

**Issue by zeeshen** [jacksontj/promxy#315]
We found the promxy APIs are slower than the prometheus servers configured as the servergroups of promxy. And the latency increases more when the query range grows.

After some debug, we found that `http.Transport` used by the server groups are configured to [disable compression](https://github.com/jacksontj/promxy/blob/master/pkg/servergroup/servergroup.go#L254). Disabling compression causing the time spent on receiving response increases. Bigger the query result, longer latency.

![image](https://user-images.githubusercontent.com/3369662/83868169-ffe13300-a75c-11ea-86b7-415e44004bba.png)
For the same query: 
Allowing compression  3.8s; Disabled: 12s. 

What's the purpose for the `DisableCompression` config here? Can we remove it?

**Comment by jacksontj** [comment]
Good catch! This seems to be left around from when the servergroup client was swapped to upstream prom client (likely from debugging). Created https://github.com/jacksontj/promxy/pull/316 to remove that line
