### ISSUE TITLE
Where can I set a port other than the default 8082 ? 

### ISSUE THREAD

**Issue by vvutharkar** [jacksontj/promxy#317]
I want promxy to bind to a port different than the default 8082. Which config entry do I set this in? Can you please provide example config ?

**Comment by jacksontj** [comment]
This can be set using the `bind-addr` [flag](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/main.go#L67) -- with this you can change the bind addr (IP and port).

**Comment by jacksontj** [comment]
I haven't seen an update here in a while, as I believe the question to be answered I'll close this out. If you have further questions feel free to re-open or create a new issue :)
