### ISSUE TITLE
Wrong query result when using subquery in combination with offset 

### ISSUE THREAD

**Issue by oOHenry** [jacksontj/promxy#319]
Hi,
when I use the following query I get a difference between promxy and the configured backend see attached screenshot. 
Query:
`avg_over_time(sum by (device) (rate(node_network_receive_bytes_total{instance="localhost:9100"}[2m] offset 24h))[1h:])`

Screenshot:
![image](https://user-images.githubusercontent.com/16702685/84747558-b643e400-afb7-11ea-9c0f-136973df8cec.png)

**Comment by jacksontj** [comment]
@oOHenry this issue should be resolved with the recent prom dep update; would you be able to re-test this on v0.0.64?
