### ISSUE TITLE
How to increase search.maxUniqueTimeseries

### ISSUE THREAD

**Issue by kengan** [jacksontj/promxy#321]
I use promxy to search data from victoriametrics  and get following errro

Error executing query: 422: error when executing query="node_cpu_seconds_total{mode=\"user\"}" for (time=1593595540736, step=30000): cannot evaluate "node_cpu_seconds_total{mode=\"user\"}": search error after reading 0 data blocks: error when searching tsids for tfss ["{__name__=\"node_cpu_seconds_total\", mode=\"user\"}"]: more than 300001 time series found on the time range [2020-07-01 09:20:10.736 +0000 UTC - 2020-07-01 09:25:40.736 +0000 UTC]; either increase -search.maxUniqueTimeseries or shrink the time range

can you tell me how to increase  search.maxUniqueTimeseries. Thank you

**Comment by jacksontj** [comment]
This option is actually VictoraMetrics side:

-search.maxUniqueTimeseries int
        The maximum number of unique time series each search can scan
(default 300000)

So to change this you'll need to add the CLI flag to victoria metrics
itself (promxy is simply proxying the error back to you).

**Comment by jacksontj** [comment]
Looks as though the email gateway didn't format that properly, re-pasting:

This option is actually VictoraMetrics side:
```
-search.maxUniqueTimeseries int
        The maximum number of unique time series each search can scan
(default 300000)
```

So to change this you'll need to add the CLI flag to victoria metrics itself (promxy is simply proxying the error back to you).

**Comment by jacksontj** [comment]
There hasn't been any response in a couple of weeks, so I hope that this already resolved your issue. If not please feel free to re-open :)
