### ISSUE TITLE
Propagate Basic Authentication 

### ISSUE THREAD

**Issue by philipfoulkes** [jacksontj/promxy#322]
I'm running Promxy as shown below. Promxy talks to two Prometheus instances, which sit behind NGINX. NGINX does TLS termination and basic authentication. We authenticate individual users in NGINX for Grafana and Prometheus.

```
                            => NGINX => Prometheus
NGINX => Grafana => Promxy
                            => NGINX => Prometheus
```

In Grafana, it's possible to pass the user's credentials to the data source. When I configure Prometheus as the data source in Grafana, I select With Credentials (as shown below), and Grafana passes the logged-in user's credentials through to NGINX/Prometheus, and all works well.

![image](https://user-images.githubusercontent.com/44870662/86511786-935d6080-bdfc-11ea-86a7-7550d0a7a365.png)

It would be nice if it was possible to send the logged-in user's credentials to Promxy (from Grafana), and then Promxy pass these along to NGINX/Prometheus. I see when I pass the credentials from Grafana to Promxy, Promxy does not pass the details along. For now, I've configured a set of credentials in Promxy, so that I can authenticate against NGINX for Prometheus.

I think it would be useful to control this behaviour of passing credentials via a flag.

**Comment by jacksontj** [comment]
First off, welcome :)

Second off, I totally agree that this would be a useful feature. It shouldn't be too hard to add, just need a middleware to capture the headers and then an option to pass them downstream. I'm not sure when I'll have time to knock this out myself, but I'll be happy to when I get some time. If anyone is interested in submitting a PR for this I'd be more than happy to review :)

**Comment by philipfoulkes** [comment]
Thank-you for the welcome @jacksontj. And thanks for Promxy. It's a great companion to Prometheus!

I'd be happy to submit a PR. I did have a brief look at the code, but I need to find a bit more time to understand how it all fits together. I see there's a weekend coming up...

**Comment by philipfoulkes** [comment]
Thanks for adding this feature @jacksontj
