### ISSUE TITLE
Not able to send the data to remote write

### ISSUE THREAD

**Issue by rutaveej-shah** [jacksontj/promxy#323]
Hello Team,

I have deployed promxy in my k8s Cluster. Every thing is working fine except I am not able to send the data to remote_writer. In the logs i couldn't find any error. I want to send the data to my Victoria Metrics endpoint.  I am not getting any error in Victoria metrics endpoint as well.

Is there any way we can check the data  that are send by promxy to Victoria Metircs. ?

Please find the below logs which I am getting from promxy.

```
time="2020-07-09T09:44:19Z" level=debug desiredShards=0.00014009046630748397 fields.msg=QueueManager.caclulateDesiredShards queue="0:https://prometheus-ext.*.*.com/api/v1/write" samplesIn=0.15591698724763245 samplesOut=0.16779071570624507 samplesPending=-0.01187372845861262
time="2020-07-09T09:44:19Z" level=debug desiredShards=0.00014009046630748397 fields.msg=QueueManager.updateShardsLoop lowerBound=0.7 queue="0:https://prometheus-ext.*.*.com/api/v1/write" upperBound=1.3
time="2020-07-09T09:44:29Z" level=debug desiredShards=0.00011207237304598719 fields.msg=QueueManager.caclulateDesiredShards queue="0:https://prometheus-ext.*.*.com/api/v1/write" samplesIn=0.12473358979810596 samplesOut=0.13423257256499604 samplesPending=-0.009498982766890082
time="2020-07-09T09:44:29Z" level=debug desiredShards=0.00011207237304598719 fields.msg=QueueManager.updateShardsLoop lowerBound=0.7 queue="0:https://prometheus-ext.*.*.com/api/v1/write" upperBound=1.3
```

**Comment by jacksontj** [comment]
Unfortunately that logging is all done in the remote_write client that promxy uses (and it sounds like the logging isn't enough :/). I actually use the remote-write functionality myself, so something must be wrong in there. I'd suggest either (1) checking tcpdump or (2) using a more basic remote-write endpoint (e.g. https://github.com/jacksontj/promxy/blob/master/cmd/remote_write_exporter/main.go) to write to to ensure that it is actually exporting data.

**Comment by jacksontj** [comment]
Actually, revisiting this I forgot I already have a fork of this library :) So adding logging is potenttially possible, although they are using a logger without a trace level (so logging each point would be too much for debug logging). However there are metrics for `promxy_remote_storage_succeeded_samples_total` for whether they are being sent -- so that should be sufficient in determining if they are sending.
