### ISSUE TITLE
Release v0.0.60 - missing linux-amd64 binary

### ISSUE THREAD

**Issue by franek1709** [jacksontj/promxy#332]
I noticed there is no linux-amd64 binary for promxy in 0.0.60 release. Is it an error?

**Comment by asteny** [comment]
Hi! Plz add linux-amd64 binary, I can't build my [deb package for promxy](https://github.com/asteny/promxy-deb)

**Comment by jacksontj** [comment]
![Screenshot from 2020-07-21 07-30-32](https://user-images.githubusercontent.com/1619869/88068708-69f34300-cb25-11ea-9b3c-355e3eaf8e52.png)
Seems that github ate my package :( I re-uploaded the release
