### ISSUE TITLE
Unable to query metrics containg a dot in their name

### ISSUE THREAD

**Issue by avanier** [jacksontj/promxy#338]
I'm probably missing something big, but I'm at my wits end here.

I'm running two VictoriaMetrics clusters fronted by Promxy. Our metrics are fed into the VictoriaMetrics clusters with Telegraf through the statsite endpoint. _(Because transitioning from another system reasons.)_

Whenever I try to query a metric that has a dot in the name, I get a parsing error.

```logfmt
10.0.0.1 - - [18/Aug/2020 21:10:26] "GET /api/v1/query HTTP/1.1 400 156" 0.000084 query=internal_write.metrics_added&start=1597769835&end=1597773435&step=15
```

```plaintext
curl -v "http://my-promxy/api/v1/query?query=internal_write.metrics_added&start=1597769835&end=1597773435&step=15" 
* TCP_NODELAY set
> GET /api/v1/query?query=internal_write.metrics_added&start=1597769835&end=1597773435&step=15 HTTP/1.1
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Date: Tue, 18 Aug 2020 21:10:26 GMT
< Content-Length: 156
< 
{"status":"error","errorType":"bad_data","error":"invalid parameter 'query': parse error at char 15: could not parse remaining input \".metrics_added\"..."}
```

Trying the same query directly into `vmselect` works as expected.

```plaintext
curl -v "http://vmselect.victoriametrics.svc.cluster.local:8481/select/0/prometheus/api/v1/query?query=internal_write.metrics_ad
ded&start=1597769835&end=1597773435&step=15"
*   Trying 255.255.255.255:8481...
* TCP_NODELAY set
* Connected to vmselect.victoriametrics.svc.cluster.local (255.255.255.255) port 8481 (#0)
> GET /select/0/prometheus/api/v1/query?query=internal_write.metrics_added&start=1597769835&end=1597773435&step=15 HTTP/1.1
> Host: vmselect.victoriametrics.svc.cluster.local:8481
> User-Agent: curl/7.67.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Date: Tue, 18 Aug 2020 21:15:43 GMT
< Content-Length: 392
< 
* Connection #0 to host vmselect.victoriametrics.svc.cluster.local left intact
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"internal_write.metrics_added","host":"telegraf-polling-service","output":"health","version":"1.14.5"},"value":[1597785313.822,"1884981097"]},{"metric":{"__name__":"internal_write.metrics_added","host":"telegraf-polling-service","output":"graphite","version":"1.14.5"},"value":[1597785313.822,"1884981096"]}]}}
```

Here are my questions:

- Is my error really related to having a dot in the metric name?
- Is there a design reason that would prevent Promxy from dealing with metric names with dots in them?
- May I ask for a lead as to where this parsing might happen? I think I might be able to PR my way through this...

**Comment by jacksontj** [comment]
> Is my error really related to having a dot in the metric name?

Very likely; prometheus doesn't allow for `.` in a metric name (https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) so it would make sense for it to error there.

> Is there a design reason that would prevent Promxy from dealing with metric names with dots in them?

Not explicitly, but promxy uses a lot of upstream prometheus libraries -- which disallow them. So its possible but ultimately not planned (as those would be "invalid" prometheus metric names). If this ends up being a small diff I would consider carrying it through on the prometheus fork.

> May I ask for a lead as to where this parsing might happen? I think I might be able to PR my way through this...

This looks like parsing in promql (so somewhere in [here](https://github.com/prometheus/prometheus/tree/master/promql/parser)) If you are able to come up with a reasonable patch I do maintain a fork that promxy uses (https://github.com/jacksontj/prometheus/tree/release-2.10_fork_promxy)

**Comment by avanier** [comment]
This is an interesting setup then... from a VictoriaMetrics point of view. Considering that you can only query it with Promql, but it allows you to insert in other formats, but complies _(albeit leniently it seems)_ to all of them, this use case is not really a valid one! :sweat_smile: 

I don't think it makes sense to extend Promql beyond what it was specified to do then. Unless you see a point in pursuing this further, I would close this issue.

_(Thanks for the really quick answer!)_
