### ISSUE TITLE
Primary and backup balancing scheme

### ISSUE THREAD

**Issue by freeseacher** [jacksontj/promxy#341]
Hi. i use promxy with two clusters of victroiametrics and due of difference how that clusters architectured i have to use in one cluster only one server with promxy. in case of maintenance if grafana pointing to that server everything goes wrong. 
Currently my grafana points to the one of clusters. 
I want to move it from `promxy on cluster side` to `promxy on server with grafana`. 
I want to keep all the things as it is now on clusters side. 

I was thinking something like primary/backup balancing scheme in servergroup ?
Or maybe that should be done on just nginx.

**Comment by jacksontj** [comment]
So to repeat (to make sure I understand the ask); it sounds like you want to be able to control which server groups are attempted (e.g. try SG1 and if it fails fall back to SG2)? If so this isn't supported today, but I'd be willing to look at a PR for it (my concern is that the configs will be a huge mess).

In the scenario above are both clusters configured with the same data etc? Or are they different? If they are the same data, I'm curious why they can't just be configured as the same servergroup? If they are different it would seem you'd want to aggregate across them?

**Comment by freeseacher** [comment]
They all have the same data, but one of them receive read workload and another don't. During deploy process i switch them like in blue/green deploy for reads. They got all writes anyway. 

From configuration point of view it can be done like this 
``
promxy:
  server_groups:
    lb_mode: flood | failover
    - static_configs:
        - targets:
          - cluster1:8082
      mode: primary
    - static_configs:
        - targets:
          - cluster2:8082
      mode: secondary
```
where `lb_mode` can be flood as done now and `failover` as proposed in that request.

**Comment by jacksontj** [comment]
So promxy today can use N different servergroups; so if we were to do something like this it would be unclear *which* are backups of others. So maybe we could have some "backup" or "failover" key inside a servergroup to allow defining another below it. So as an example:


```
promxy:
  server_groups:
    lb_mode: flood | failover
    - static_configs:
        - targets:
          - cluster1:8082
      failover:
        static_configs:
          - targets:
            - cluster2:8082
```

This would allow for whatever nesting people want while maintaining structure on the various servergroups. The downside with this failover stuff in general (not specific to this config) would be that we'd have to define what scenarios a failover would happen. Presumably it would failover after getting errors from the primary servergroup -- but in the case above where you want blue/green that would mean you'd either have to reconfigure promxy (swap primary and failover) or take the primary one down to force the failover.


As you mentioned above this could be covered with another proxy (e.g. NGINX) in front of promxy, which may end up being less complicated.

**Comment by freeseacher** [comment]
yep. tnx. looks like using nginx in front of promxys is what i really want.
