### ISSUE TITLE
/metrics endpoints

### ISSUE THREAD

**Issue by proffust** [jacksontj/promxy#342]
Hello!
/metrics not described in the documentation, plus I would like to see a dashboard for monitoring promxy

**Comment by matejzero** [comment]
I might take a bite at this. Looking at the metrics, I only see 2 relevant metrics: `server_group_request_duration_seconds_sum` and `server_group_request_duration_seconds_count`.

Prometheus metrics are probably not usable on the dashboard, right?

**Comment by jacksontj** [comment]
Some metrics from prometheus are available (as an example the promql ones) as promxy uses a lot of the prometheus library to handle various parts (promql, web API, etc.). So documentation + dashboard here should cover metrics that are relevant to promxy's performance.

**Comment by jacksontj** [comment]
Example dashboard was added to repo: https://github.com/jacksontj/promxy/pull/468
