### ISSUE TITLE
When using Prometheus datasource in grafana and pointing to a Promxy instance , the browser mode of access throws error

### ISSUE THREAD

**Issue by vvutharkar** [jacksontj/promxy#344]
In grafana when configure prometheus type datasource (or any datasource) one can configure the access mode as 'Server' or 'Browser' . In browser mode the requests to datasource go directly to the target url from the browser .

 For regular prometheus url endpoint both the Server (proxy) / Browser mode configurations work when defining and testing the datasource from Grafana UI. 

But when Promxy endpoint is specified and Browser access mode is selected,  I get the error 

"Cannot read property 'status' of undefined"

It works fine if I switch to Server access mode.  What is going wrong in Browser access mode?  The reason I need browser access mode to work for the promxy endpoint is that there are corp brower/proxy settings that are configured, and it is simpler if the datasource is accessed directly from browser, when it can use the configured proxy settings in the browser. If server mode is specified, then I have to ensure my grafana server is deployed in the same environment as where my promxy and other PROD apps are deployed. Either that or proxy settings configured on the server side so grafana pod can access the promxy pod. This is not always possible. Browser mode access simplifies a lot of these things. Not sure why it does not work for promxy endpoint. Can someone throw some light please?

**Comment by jacksontj** [comment]
Thanks for the report! Promxy should definitely be working in both browser and server mode (you use 'browser" mode effectively when you use the promxy UI directly. From the error you pasted above (cannot read property status of undefined) it sounds like you have some error in the browser (sounds like its a COORS header issue, but could be something else). I'd suggest looking into the developer tools of the browser to see what the error there is. Given that its "undefined" it sounds like the response is being blocked for some reason -- if not then the developer tools should show you what the API call and response was -- and if you could include those here it would help with debugging :)

**Comment by vvutharkar** [comment]
@jacksontj  Yes, looks like it is CORS issue

Access to XMLHttpRequest at 'https://promxy.vip.company.com/os/api/v1/query?query=1%2B1&time=1600798224.318' from origin 'https://grafana.company.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.     ( I anonymized my company domain)  

So why is this header not getting set when making requests from grafana to Promxy. But the header is set to "Access-Control-Allow-Origin: *" When I have a datasource that is pointing to regular prometheus endpoint?  Is this a setting on promxy that I need to set? So it allows CORS requests?

**Comment by vvutharkar** [comment]
Seems like promxy must set `Access-Control-Allow-Origin: *` header in its response back to grafana, so that the browser understands that CORS request to promxy is allowed and succeeds. This is something to be set on Promxy side , and not on  grafana (or browser) side if I understand correctly

**Comment by teochenglim** [comment]
@vvutharkar you can also put promxy behind a haproxy/nginx to archive that. But it would be nice promxy understand whether or not it is behind a load balancer/proxy or not and forward the appropriate headers and so on.

**Comment by jacksontj** [comment]
Since the CORS header stuff is implemented in prometheus it was trivial to add direct support in promxy (#353 ) -- so that should remove the need for additional proxies in the middle to manage the CORS headers.
