### ISSUE TITLE
Can I use timescale-prometheus as the remote-write target for Promxy?

### ISSUE THREAD

**Issue by vvutharkar** [jacksontj/promxy#346]
https://github.com/timescale/timescale-prometheus , Can I use this as the remote-write target for Promxy?  Can you please point me to documented steps/instructions on how to setup and configure remote-write plugin in Promxy? 

Thank you!

**Comment by vvutharkar** [comment]
Also, can I configure more than one remote-write endpoint , so that promxy sends same data to redundant (cross DC) targets  for data center level redundancy.

**Comment by jacksontj** [comment]
@vvutharkar promxy can send to anything that implements the remote_write interface from prometheus. From a quick skim of the link you provided it seems that it would work. [Here](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L22) is an example of how to configure remote_write (keep in mind this is for promxy-generated metrics such as recording rules).

> Also, can I configure more than one remote-write endpoint , so that promxy sends same data to redundant (cross DC) targets for data center level redundancy.

Yes, this is the same remote_write configuration that upstream prometheus supports which includes multiple targets.

**Comment by jacksontj** [comment]
I believe this question is answered, if not please feel free to reopen!
