### ISSUE TITLE
Allow relabelling for the path-prefix

### ISSUE THREAD

**Issue by QuentinBisson** [jacksontj/promxy#347]
With our current setup (a management cluster and multiple user clusters), we have a prometheus per cluster and every prometheus have its own path (the id of the cluster).
The prometheus share the same config apart from the path so being able to relabel the path prefix would help us tremendously, otherwise, we need to edit the configmap to add a server group for every new cluster. Would it make sense to allow relabelling of the path prefix instead of setting it in the configmap as this value is dynamic for us?

**Comment by jacksontj** [comment]
This seems like a reasonable ask; From a quick think about it this should be a relatively simple change -- PRs definitely welcome :) Otherwise I'll try to pick this up once I get some time.

**Comment by jacksontj** [comment]
Looks like this is covered by the merged PR, closing :)
