### ISSUE TITLE
http access to metrics endpoint results in log messages even at ERROR  logging level

### ISSUE THREAD

**Issue by vvutharkar** [jacksontj/promxy#348]
For self monitoring, I have a prometheus instance that scrapes all my Promxy instances every few seconds. 
In the stdout log I see messages like below  everytime the metrics endpoint is scraped (IP addr anonymized to a.x.y.z)

These messages get logged whether at info level or warn or even error.  I think these informative logging should only happen at debug level or at most INFO level, but definitely not at WARN or ERROR . Please fix this excessive logging issue.

" a.x.y.z - - [02/Oct/2020 04:17:10] "GET /metrics HTTP/1.1 200 4084" 0.003576
a.x.y.z  - - [02/Oct/2020 04:17:12] "GET /metrics HTTP/1.1 200 4091" 0.003376
a.x.y.z - - [02/Oct/2020 04:17:15] "GET /metrics HTTP/1.1 200 4137" 0.003011"

**Comment by jacksontj** [comment]
This is actually indended behavior. What you are seeing is a combination of leveled log output (e.g. WARN, ERROR) as well as access logs (request from IP to path). You can control the log levels and outputs through CLI flags and you can also control where the access log goes (https://github.com/jacksontj/promxy/pull/77) to control the log volume and destination.
