### ISSUE TITLE
Remote storage queue full, discarding sample 

### ISSUE THREAD

**Issue by vvutharkar** [jacksontj/promxy#349]
I have configured promxy to remote_write to victoria metrics cluster.

Periodically in the stdout logs I see, 

time="2020-10-02T04:22:23Z" level=warning fields.msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed.

What is the impact of this? Does this mean some time series samples are actually getting skipped/discarded and not being sent to the remote_write destination?  OR is there a retry mechanism?

What are some ways to avoid this or at least reduce this ?  Is it the volume of metrics being sent to the remote Victoria Metrics cluster? I thought VM is capable of very high ingestion rate, As per https://medium.com/@valyala/when-size-matters-benchmarking-victoriametrics-vs-timescale-and-influxdb-6035811952d4 , VictoriaMetrics — 1.7M datapoints per second, RAM usage — 0.8GB, data size on HDD — 387MB.  I am no where close to sending that many data points.  Is this an issue on the VM side , or on the remote_write plugin side?

**Comment by jacksontj** [comment]
This log message comes from the remote_writer in promxy. The way that writer works is that it queues messages locally and sends them out. So if this is getting full and dropping messages (as it says in the log) then either (1) the remote end isn't accepting them fast enough, (2) the local buffer isn't large enough to handle the RTT, or (3) the parallelism of the sending -- how many queues-- isn't high enough. All of these options are configurable in the remote_write configuration.

**Comment by jacksontj** [comment]
There hasn't been a response on this issue in a while; so I'm going to assume it is resolved. If you have further questions feel free to re-open :)
