### ISSUE TITLE
Update Prometheus dependency

### ISSUE THREAD

**Issue by mig4** [jacksontj/promxy#352]
Hi 👋 

We're building an operator in Go and we want it to configure promxy among other things. For this reason we wanted to be able to (de-)serialise promxy config from Go and looked at using the [github.com/jacksontj/promxy/pkg/servergroup.Config](https://github.com/jacksontj/promxy/blob/master/pkg/servergroup/config.go) struct. Unfortunately since promxy currently depends on `prometheus v1.8.1` it is not playing well with our build as we depend on v2.

Would you consider a PR updating the Prometheus dependency to v2?

**Comment by jacksontj** [comment]
This is actually quite weird; promxy is using a fork of prometheus that I maintain (https://github.com/jacksontj/prometheus/tree/release-2.10_fork_promxy). Whats more weird is that the version in go.mod has the correct SHA for the fork (which is 2.10 based) so I'm not sure why its showing up as 1.8.1 in go.mod.

I spent a little time looking into this but I don't see anything obvious; so this seems to be some go.mod issue (as the code is actually the 2.10 based fork). Although as I'm thinking about it now maybe the fork vs upstream might pose a similar issue for your project.

**Comment by psalaberria002** [comment]
There were some new features added in 2.16 https://www.robustperception.io/new-features-in-prometheus-2-16-0

What's the process of upgrading that dependency?

**Comment by jacksontj** [comment]
Updating the dep would require upgrading the fork above; so a PR to my fork would be the way to go (this requires forward-porting the features for nodereplacer etc. that make promxy work). Whenever I get around to this I usually just update to the latest released version base (as of this writing its 2.22) -- usually I find some bug(s) in upstream we have to fix at the same time; so unfortunately its not always a trivial task :/

**Comment by jacksontj** [comment]
That being said, the initial use-case shouldn't be blocked by the upgrade (as the version we are on is high enough) so if anyone has an idea on how to get go mod to properly set the dep version that would also be helpful :)

**Comment by R4scal** [comment]
Hi

Are there any plans for this? I would like to use promxy, but half of the requests in grafanа was breaking when switching traffic to it

**Comment by jacksontj** [comment]
WIP PR to move to 2.24 fork prometheus -- https://github.com/jacksontj/promxy/pull/378 (some more details in the PR)

**Comment by jacksontj** [comment]
prom dep has been updated and is included in the 0.0.63 release https://github.com/jacksontj/promxy/releases/tag/v0.0.63
