### ISSUE TITLE
Alerts are reset after upgrading\restarting promxy

### ISSUE THREAD

**Issue by sagor999** [jacksontj/promxy#358]
Hi,

Is there any way to keep alerts persistent between restarts of promxy? 
Each time I upgrade or restart promxy container, all alerts are reset and then re-fire. 

Thank you!

**Comment by jacksontj** [comment]
This is unfortunately a known issue. The detail for it is covered in #50 -- this is something I'd like to add; unfortunately it requires either persistent storage (problematic since promxy is otherwise stateless) or changes to prometheus libraries (to add backfilling of alerts).

**Comment by sagor999** [comment]
Ah, thank you. Sorry for duplicate. I will close this one then.
