### ISSUE TITLE
Promxy returns error if one of the servers in servergroup is not accessible

### ISSUE THREAD

**Issue by vvutharkar** [jacksontj/promxy#365]
I have a server group with HA pair.  Primary of the HA pair in one zone and other in second zone.   I have noticed that when zone 2 instance is down, that is in each server group only the primary instance of the HA pair is reachable, promxy fails to return results for any query.  

Qyery page shows:  "Error loading available metrics! "

and Recording rules show 

" ERR | server_error: server error: 503"

Promxy should work even if one of the instances in HA pair is unreachable, right?  Granted that means results are not merged and there may be holes in data. But it should still work with degraded behavior?  Does promxy expect that both instances of an HA Pair are reachable , to return back usable result?  That goes contradictory to the spirit of HA pair. We have HA pair in anticipation that one instance might be down at a give time. 

The problem is exacerbated with I have serveral server groups fronted by promxy. And in each HA pair, either a zone 1 or zone 2 instance is bad but not all from same zone. I expect promxy to be able to return available results from surviving instance of each server group. Right?

**Comment by jacksontj** [comment]
Promxy should not return an error if only one of the downstreams is unavailable. Unfortunately this report doesn't include enough information to debug anything. Could you please include (1) the config file (2) trace logs (3 -- optional) tcp dump of the query/response.

**Comment by jacksontj** [comment]
There hasn't been any update on this case in a while, so I'm going to close this out. If this is still an issue please feel free to re-open!
