### ISSUE TITLE
update ui to new prometheus ui ?

### ISSUE THREAD

**Issue by freeseacher** [jacksontj/promxy#367]
It seems withhttps://github.com/prometheus/prometheus/releases/tag/v2.23.0 new prometheus ui is default 
Can you please update ui to new one ?

**Comment by jacksontj** [comment]
WIP branch to upgrade -- https://github.com/jacksontj/promxy/pull/378

This has been a bit more work than I anticipated so it will likely take a bit more work; but the functionality all seems to be there as of now :)

**Comment by jacksontj** [comment]
Done! https://github.com/jacksontj/promxy/releases/tag/v0.0.63
