### ISSUE TITLE
Kubernetes Controller to manage the configmap

### ISSUE THREAD

**Issue by QuentinBisson** [jacksontj/promxy#374]
When we have to manage dynamic prometheus instances, having to manage the promxy configmap with code can be painful.

I was thinking creating a simple controller that reconciles ServerGroup CR into the promxy configmap would help in this case. We could use the ingress controllers (nginx-ingress-controller ) or prometheus-operator as examples.

@jacksontj as this would be fully dependent on promxy, would you rather I start a new project outside of this or create it in the promxy repository directly?

**Comment by jacksontj** [comment]
I would actually suggest using the relabel_rules with discovery to achieve this. In this case you can create server groups "dynamically" based on labels that exist. An example of such usage can be found here: https://medium.com/wish-engineering/horizontally-scaling-prometheus-at-wish-ea4b694318dd Basically the 'grouping' in the servergroup is just done by the uniqueness of labels; so as long as you don't need a lot of other configuration (which generally is true) the rest can just be auto-discovered through whatever discovery mechanism you use.

Assuming you still wish to create some operator pattern for this; I'm thinking it would require a bit more integration potentially? Just changing the config map isn't sufficient; you'd have to actually hit the reload endpoints on all the promxy hosts as well (they don't watch for config changes) -- although I imagine the prometheus operator deals with the same issue (and might be a better operator to start from?). I'm not opposed to the operator joining this repo; but probably easiest to start it as a separate project or at least branch (to enable easier iteration).

**Comment by jacksontj** [comment]
I _think_ this is resolved with the relabel feature added-- so I'm going to close this out. If that is not the case please re-open and we can continue any further discussion!
