### ISSUE TITLE
What version of prometheus do promxy use?

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#376]
I think it's better to write what version of prometheus is used in readme.

**Comment by jacksontj** [comment]
Its using a fork of 2.10 right now; although the particular version that promxy is using isn't a _huge_ issue for users (it just defines what version of the promql engine we have, but the APIs etc should be compatible across versions). So i'm not opposed to people knowing what version we use; but it also shouldn't be _that_ important for end-users.

**Comment by Wing924** [comment]
@jacksontj thank you for replying my issue.
I ask prometheus version because:
- newer version of prometheus add some sd config.
  - e.g. `selectors` in kubernetes_sd_config
- newer version of prometheus improved promQL.
  - e.g. `@` modifier, sub-query

**Comment by jacksontj** [comment]
True; as of now I just updated the prom dep to 2.24; the version is defined in the `go.mod` file but for some reason its a non-obvious verison there (some psuedo version).
