### ISSUE TITLE
promxy v0.0.64 docker image don't exist on quay.io

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#384]
```
-> % docker pull quay.io/jacksontj/promxy:v0.0.64                                                                                                       (jpe2-caas1-prod1-He Wei-mon-aas-prod/mon-aas-prod)
Error response from daemon: manifest for quay.io/jacksontj/promxy:v0.0.64 not found: manifest unknown: manifest unknown
```
Recent Repo Builds looks failed.

**Comment by jacksontj** [comment]
Thanks for filing the ticket! It seems we're hitting the dreaded dockerhub rate-limiting on quay builds. I'm swapping the build stuff over to github actions (since it has caching built in); so once #385 is in build should resume.

**Comment by jacksontj** [comment]
As of v0.0.66 builds have moved to github images (which pushes to quay); so this should all be resolved!
