### ISSUE TITLE
Recording rule doesn't work after upgrading from 0.0.62 to 0.0.66

### ISSUE THREAD

**Issue by yuriydzobak** [jacksontj/promxy#388]
Hi,
Thank you for upgrade the prom lib
I faced the issue, I can't run promxy with record rules, alerts are working fine
The error aspires when I enabled the block in config file
```
 rule_files:
   - /record/*.yml
```

```
time="2021-02-04T07:50:56Z" level=error msg="failed to apply configuration: promxy doesn't support recording rules: record: hour_of_the_day\nexpr: hour()\n"
time="2021-02-04T07:50:56Z" level=fatal msg="Error loading config: one or more errors occurred while applying new configuration"
```

**Comment by jacksontj** [comment]
This particular error is only when no remote write configuration exists (https://github.com/jacksontj/promxy/blob/master/cmd/promxy/main.go#L301); Can you provide your config file? Looks like remote write is just missing.

**Comment by yuriydzobak** [comment]
> This particular error is only when no remote write configuration exists (https://github.com/jacksontj/promxy/blob/master/cmd/promxy/main.go#L301); Can you provide your config file? Looks like remote write is just missing.

got it, thx
Yes, remote write missed, because I have the same issue https://github.com/jacksontj/promxy/issues/386 
=)

**Comment by jacksontj** [comment]
@yuriydzobak Good to hear its not _another_ issue :) I'm working on #387 which fixes the panics reported-- should land shortly.
