### ISSUE TITLE
promxy related to prometheusrule 

### ISSUE THREAD

**Issue by briskjj** [jacksontj/promxy#390]
I deploy prometheus by prometheus-operator and use sharding capability， i want to get alerts by promxy,  but i'm not sure whether the proxy can automatically associate prometheusrule  crd. or whether it can be supported in the near future. thanks

spec:
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: example

**Comment by jacksontj** [comment]
This depends on how the controller is implemented. From a quick read of the README it seems that the operator maintains a proemtheus config file based on the various CRDs. If so then you might be able to just have promxy pointed at the same configmap etc. I don't see anything in the README about direct integration with prometheus-- so I don't think there'd be work required in promxy to support this (so it might just work out of the box?).

**Comment by briskjj** [comment]
Thank you for your response, configmap is ok, the thanos-ruler has been integrated to the prometheus-operator.

**Comment by jacksontj** [comment]
If configmap is okay and the operator already has support for configmap managing -- in theory it should just work together (since the operator presumably maintains a configmap of alerts; so you should be able to configure promxy to read that in).

**Comment by jacksontj** [comment]
There's been no update for a while; so I'm hoping this was sufficient. If not please feel free to re-open!
