### ISSUE TITLE
Web UI build instructions

### ISSUE THREAD

**Issue by prymitive** [jacksontj/promxy#393]
It seems that the web UI is not working for me in the 0.0.67, I'm getting `open static/react/index.html: no such file or directory`. It's likely due to the new React UI in latest Prometheus, which might require some extra build steps, but I don't see any mention of that in docs. Is it possible to get the UI working?

**Comment by prymitive** [comment]
I need to pass `-tags netgo,builtinassets` when building the binary, UI works after that

**Comment by jacksontj** [comment]
For posterity; the builds are currently done both in the [dockerfile](https://github.com/jacksontj/promxy/blob/master/Dockerfile) and in a [bash script](https://github.com/jacksontj/promxy/blob/master/build.bash#L26) to find flags :)
