### ISSUE TITLE
/federate always returning empty response in 0.0.67

### ISSUE THREAD

**Issue by prymitive** [jacksontj/promxy#397]
0.0.67 release doesn't seem to work, throwing errors on some views, but after adding 2 commits made after 0.0.67 tag I've manage to get the UI to work without any errors.
But when I send any request to /federate with `match[]={job="prometheus"}` I always get an empty reply, querying for `{job="prometheus"}` via promxy UI gives me correct results.

**Comment by jacksontj** [comment]
> 0.0.67 release doesn't seem to work, throwing errors on some views, but after adding 2 commits made after 0.0.67 tag I've manage to get the UI to work without any errors.

I assume the issues were with the classic UI? The 2 patches after the release are just to resolve issues with the classic UI, the react UI should work just fine (although if you are building it yourself there are some new flags required in the compile command).

>  But when I send any request to /federate with match[]={job="prometheus"} I always get an empty reply, querying for {job="prometheus"} via promxy UI gives me correct results.

AFAIK this hasn't ever worked within promxy. The reasoning was that promxy more or less removes the need for this federation (For anyone else: federation endpoints basically expose current metric values as a scrape target for some other prometheus server to scrape).


Although I think its generally not a good idea to use the federate endpoint, I don't see why we can't make it work. I set this up locally and was able to repro the issue (details in #398), so once that lands this should be fixed :)

**Comment by prymitive** [comment]
The react UI (which is now default in Prometheus, didn't try classic) worked but was throwing errors because some API calls it was using were returning errors (with go stack traces). I believe that both UIs use same API endpoints so I would assume that both would have same problem.

Federation worked well for me with 0.0.62 and it allows to have a single HA target for /federate requests when pulling metrics form an HA pair of Prometheus servers. Without promxy I need to federate from both Prometheus instances which results in duplication in federating Prometheus.

Thanks!

**Comment by prymitive** [comment]
FYI I do see that /federate requests return 500 with those 2 patches in master branch, so a new release would be appreciated

**Comment by jacksontj** [comment]
> The react UI (which is now default in Prometheus, didn't try classic) worked but was throwing errors because some API calls it was using were returning errors (with go stack traces). I believe that both UIs use same API endpoints so I would assume that both would have same problem.

You are correct that the underlying APIs are the same; so if there were panics/500s then they would impact.

> Federation worked well for me with 0.0.62 and it allows to have a single HA target for /federate requests when pulling metrics form an HA pair of Prometheus servers. Without promxy I need to federate from both Prometheus instances which results in duplication in federating Prometheus.

Good to know (I didn't ever test that and am not aware of others doing the same); easy fix at least :)

> FYI I do see that /federate requests return 500 with those 2 patches in master branch, so a new release would be appreciated

I assume you mean that you don't? If you do I'd need some info to fix :) I working on making https://github.com/jacksontj/promxy/releases/tag/v0.0.68 right now; should be done momentarily :)
