### ISSUE TITLE
Access log query param truncated

### ISSUE THREAD

**Issue by freeseacher** [jacksontj/promxy#401]
Hi.
Could we please extend or make configurable https://github.com/jacksontj/promxy/blob/7621c9db1dc809ad10217fc4d58713d8ec519ae7/pkg/logging/logging.go#L16

I want to get all the query in logs. Some large queries does not fit, other are cut in pretty interesting places and can be misleading. 

Today i got pretty strange system behavior and found that we have some queries that started from 

```
10.7.0.21 - - [06/Mar/2021 21:44:02] "POST /api/v1/query_range HTTP/1.1 200 653" 0.116664 query=histogram_quantile%280.95%2C+sum%28rate%28s........+by+%28route%2Cmethod%2Cle%29+%3E+0%29&start=161506674
```
so start date was somewhere around year 1975. 
That was not the root cause of problem but looks annoying

**Comment by jacksontj** [comment]
Definitely seems like a reasonable ask. This should be relatively easy to pick up; PRs are definitely welcome!
