### ISSUE TITLE
error: expected type range vector got instant vector

### ISSUE THREAD

**Issue by dnull88** [jacksontj/promxy#404]
Some queries through promxy returns error, but when querying VictoriaMerics directly - its ok, no errors.

Examples of queries:
_sum(increase(account_monitoring_kpi_header{kpi_header="subscribe_now_click"})) by (kpi_header)_
_increase(account_monitoring_subscription_and_payment)_ 

returns: **"parse error at line 4, char 2: expected type range vector in call to function \"increase\", got instant vector"**

How to debug what the problem?

**Comment by jacksontj** [comment]
I'd suggest attaching `trace` level logs too the case; from there its usually easy enough to debug (as it will include the queries it sent downstream, what it got back, etc.).

**Comment by jacksontj** [comment]
This was _likely_ the same underlying issue as #409 -- so I expect it to be fixed on master.
