### ISSUE TITLE
Promxy no longer shows all values in a range vector query, just the latest value

### ISSUE THREAD

**Issue by steffersaurus** [jacksontj/promxy#409]
v0.0.59 of promxy is working as expected when querying a metric range vector, i.e. `<metric_name>[7d]` will return all the data points collected for that metric over 7 days.

v0.0.64+ will only return the latest value for that metric regardless of the range vector timeframe specified. (We didn't try v0.0.60-v0.0.63). Is this new behavior intended? Is there a way to return all the values in a range vector query?

**Comment by jacksontj** [comment]
Thanks for the report! I can reproduce the issue and this is definitely a bug (TLDR; prom upstream completely redid how matrix selectors worked, and apparently there isn't a single integration test!).

**Comment by steffersaurus** [comment]
Thanks for the speedy response!
