### ISSUE TITLE
Error in deployment - panic: WHAT

### ISSUE THREAD

**Issue by kotire** [jacksontj/promxy#424]
Hi!
I`m want to run a promxy in k8s for prometheus cluster and I get this type of error when my deployment runs:

```
panic: WHAT

goroutine 1 [running]:
github.com/jacksontj/promxy/pkg/proxystorage.(*ProxyStorage).ApplyConfig(0xc000176120, 0xc000220690, 0xc000220690, 0x0)
        /go/src/github.com/jacksontj/promxy/pkg/proxystorage/proxy.go:123 +0x6fa
main.reloadConfig(0xc00084e1a8, 0xc0000b8580, 0x5, 0x8, 0x8, 0x30ff420)
        /go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:117 +0xb4
main.main()
        /go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:384 +0x18fc

```

I have a default configmap from this example - https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml

Can you help me to understand where is my config wrong or this is a bug?

**Comment by jacksontj** [comment]
This was a bug in an older version of promxy; this panic is no longer in the code -- what version of promxy are you running?

**Comment by jacksontj** [comment]
Since there has been no update in a while I'm going to assume this issue was resolved. If not please re-open and we'll pick up where we left off.
