### ISSUE TITLE
How to Setup Trace Logs

### ISSUE THREAD

**Issue by gokulkrish21** [jacksontj/promxy#428]
Need help in setting trace logs. How do we setup trace logs in Promxy. On the forum, it is mentioned on several places, there are different levels which can be set. I dont find an answer on how to set it up. I dont find it on the documentation as well.  Where do we configure the logs. Can someone post with an example.

**Comment by autokilla47** [comment]
@gokulkrish21 in docker i start container with:
    command:
      - --log-level=trace

**Comment by gokulkrish21** [comment]
Thanks. That works. Do you know what are all the possible values for that. I have found trace, info and debug so far

**Comment by autokilla47** [comment]
@gokulkrish21 + worning imho

**Comment by jacksontj** [comment]
The log levels come from logrus (https://pkg.go.dev/github.com/sirupsen/logrus#pkg-variables), soL panic, fatal, error, warn, info, debug, trace.
