### ISSUE TITLE
How-to Promxy through HTTPS?

### ISSUE THREAD

**Issue by szilardszabolcs** [jacksontj/promxy#429]
Hello, just a quick question, any answer would be appreciated, I haven't found anything based on my request yet.

We have a simple scenario, a two node Prometheus with TLS settings (.cer + .key file), we need to set the Promxy access with TLS, we must use Granafa datasource with https.
Can you please give us a hint with a sample configuration on how can we do this?

Thanks in advance!

**Comment by jacksontj** [comment]
As of right now promxy doesn't listen on https at all (upstream prom doesn't either). There is another issue (https://github.com/jacksontj/promxy/issues/432) to add support, but in the interim you could add an HTTP proxy in front of promxy to handle TLS (a few people have reported doing so).
