### ISSUE TITLE
Proxy broken since version 0.0.58

### ISSUE THREAD

**Issue by hasso** [jacksontj/promxy#431]
Since 0.0.58 my nginx proxying setup doesn't work – every query to promxy gets 302 redirect to /promxy/. It's OK in 0.0.57. It doesn't like subpath? Or am I doing something wrong?

Promxy is executed:

```
promxy --bind-addr=127.0.0.1:9082 --web.external-url=https://fqdn.host.name/promxy
```

Nginx configuration (standard):

```
location /promxy/ {
  proxy_set_header X-Real-IP  $remote_addr;
  proxy_set_header X-Forwarded-For $remote_addr;
  proxy_set_header Host $host;
  proxy_pass http://127.0.0.1:9082/;
}
```

**Comment by jacksontj** [comment]
I was able to start `master` locally with `--web.external-url=http://localhost:8082/promxy` on the CLI and it seems to work properly (I'm able to load the pages). So to debug this further we'll need more insight into what redirects you are seeing and who is sending them (nginx or promxy).

**Comment by hasso** [comment]
OK. I found out that since 0.0.58 a proxy must not strip path from requests sent to promxy. Up to 0.0.57 it worked fine and --web.external-url was really used only to generate links in UI. But since 0.0.58 promxy expects all requests to use a path portion from --web.external-url as well. With out it it answers with "302 /path/".

So in case of nginx configuration above it was enough to change `proxy_pass http://127.0.0.1:9082/;` to `proxy_pass http://127.0.0.1:9082;`.
