### ISSUE TITLE
mTLS support in promxy

### ISSUE THREAD

**Issue by warshawd** [jacksontj/promxy#432]
Hi there,

My team is using promxy and it's been great for us, but one feature we would really like to see is mTLS support for more secure communications.  We saw prometheus added support for this recently (https://github.com/prometheus/prometheus/commit/5b4f46a348ae3bc143629f25f0f997f39f30c2c2).  We're happy to submit a PR with this, but we first wanted to check if you had any opinions about the best way to implement it.  

Thanks for a great tool!

**Comment by jacksontj** [comment]
If upstream has added it to the handler I'm not opposed to pulling it in. Historically I've been leaving this out as its trivial to front promxy with some HTTP proxy to do this -- but I'm all for getting it in, PRs definitely welcome!

**Comment by jerrybelmonte** [comment]
We have some options on how we would go about implementing this. One of the options would be to go the prometheus `web.config` route which is an additional config file passed in at startup https://github.com/prometheus/prometheus/blob/main/docs/configuration/https.md . The other would be to add a `tls_config` property to the existing promxy config here https://github.com/jacksontj/promxy/blob/11457a8b415e1fa4956e05d325fd189e9e1ad23f/cmd/promxy/config.yaml#L31 . Do you have a preference? @jacksontj

**Comment by jacksontj** [comment]
No strong preference from my side; either seems fine (first being "more prometheus" and second being "more go").
