### ISSUE TITLE
Promxy is dropping samples when writing via remote_write to Victoria Metrics

### ISSUE THREAD

**Issue by vvutharkar** [jacksontj/promxy#434]
In the promxy logs I see messages like

time="2021-06-04T21:01:41Z" level=warning fields.msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed." queue="0:http:// < my domain>:8480/insert/0:0/prometheus/api/v1/write"

And also the promxy /metrics page shows the below  (sanitized my domain name for privacy)

Seems no failed samples. Those that are sent are going successfully. But quite a few being dropped without even attempting sending, due to queue being full.   The remote storage queue length shows 0. Not sure what it means. Are any promxy config params or startup args need to be tweaked so that there is enough queue length and samples are not dropped?

```
promxy_remote_storage_dropped_samples_total{queue="0:http:// <my domain>:8480/insert/0:0/prometheus/api/v1/write"} 181245

promxy_remote_storage_failed_samples_total{queue="0:http://<my domain>:8480/insert/0:0/prometheus/api/v1/write"} 0

promxy_remote_storage_queue_length{queue="0:http://<my domain>:8480/insert/0:0/prometheus/api/v1/write"} 0

promxy_remote_storage_shard_capacity{queue="0:http://<my domain>:8480/insert/0:0/prometheus/api/v1/write"} 10

promxy_remote_storage_shards{queue="0:http://<my domain>:8480/insert/0:0/prometheus/api/v1/write"} 1

promxy_remote_storage_succeeded_samples_total{queue="0:http://<my domain>:8480/insert/0:0/prometheus/api/v1/write"} 2.23264e+06```

**Comment by Vladikamira** [comment]
@vvutharkar  In your case, the remote_write's queue is full, that's why it drops samples.
I'm not an expert here, but afaik Promxy is using Prometheus's library for remote writing, so you can play with options like `max_shards` or `min_shards` [more docs here](https://prometheus.io/docs/practices/remote_write/#max_shards) and try to increase amount of queues or increasing queue size. I hope it will help you

**Comment by jacksontj** [comment]
Thanks @Vladikamira -- your assessment here is accurate :)

**Comment by jacksontj** [comment]
There hasn't been a response on this issue in a while; so I'm going to assume it is resolved. If you have further questions feel free to re-open :)
