### ISSUE TITLE
Some problems about proxy

### ISSUE THREAD

**Issue by ktpktr0** [jacksontj/promxy#441]
I am a novice of proxy, I would like to ask a few questions

1. If you need to use alerts, you need to define them in the proxy configuration?

2. Remote of proxy configuration_ Does write have the same proxy as Prometheus?

3. When using k8s to install Prometheus (multiple copies), the SVC address is the unified entry, is promxy optional?

4. Do the above related configurations need to be configured in the Prometheus?

5. Is the grafana configuration data source http://localhost :8082?

**Comment by jacksontj** [comment]
> If you need to use alerts, you need to define them in the proxy configuration?

Alerts in promxy work the same as in prometheus; the config file specifies `rule_files` (https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L11) to be loaded

> Remote of proxy configuration_ Does write have the same proxy as Prometheus?

remote_write for promxy uses the same API as prometheus; its uses for metrics and recording rules (details in example config -- https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L22)

> When using k8s to install Prometheus (multiple copies), the SVC address is the unified entry, is promxy optional?

A combined serviceIP in k8s will send  your request to *a* prometheus box but doesn't handle aggregating between the 2 (if they have different data) or filling in holes if one was down (if they have the same data). Why promxy is covered in the README in more detail -- https://github.com/jacksontj/promxy#why-promxy

> Do the above related configurations need to be configured in the Prometheus?

They don't need to be unless you want the functionality on the prometheus side

> Is the grafana configuration data source http://localhost :8082?

I'm not quite sure what you are asking here. Presumably this isn't a local grafana and local promxy -- so "no". Promxy listens on whatever interface/port you configure (by default port 8082) -- so this is entirely up to you.

**Comment by ktpktr0** [comment]
Thank you for your answer
