### ISSUE TITLE
Promxy: Metric aggregation

### ISSUE THREAD

**Issue by ravibhooshan** [jacksontj/promxy#442]
Hi - I am setting up promxy first time and have some question.
My Setup:
2 Prometheus nodes - each runs dockerized  Prometehus, Exporters & Promxy.
Promxy Configuration:
promxy:
  server_groups:
    - static_configs:
        - targets:
          - habcda1:9090
          - habcd2:9090
      labels:
        sg: SAH_HA
      anti_affinity: 10s
      remote_read: false
      remote_read_path: /api/v1/read
      query_params:
        nocache: 1
      scheme: http
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true

But when I pull a metric from Promxy UI or Grafana (Datsources is mapped to Promxy), I get 2 result for any metrics one from each Prometheus node. Like below:
![image](https://user-images.githubusercontent.com/11981903/123104292-d006db00-d404-11eb-8103-2e91daa4171f.png)

But my understanding is that Promxy should aggregate the result from both downstream Prometheus and show a single result for user, am I wrong or something is wrong in my configuration.

**Comment by jacksontj** [comment]
Your expectation here seems accurate; if you have multiple nodes behind promxy with the same labels (or in the same servergroup) they should be deduped. This is easily shown with the following config:

```
promxy:
  server_groups:
    - static_configs:
      - targets:
        - demo.robustperception.io:9090
        - demo.robustperception.io:9090
      http_client:
        dial_timeout: 1s
```

http://localhost:8082/promxy/api/v1/query?query=prometheus_build_info&time=1625181149.085
```
{
	"status": "success",
	"data": {
		"resultType": "vector",
		"result": [{
			"metric": {
				"__name__": "prometheus_build_info",
				"branch": "HEAD",
				"goversion": "go1.16.4",
				"instance": "demo.robustperception.io:9090",
				"job": "prometheus",
				"revision": "db7f0bcec27bd8aeebad6b08ac849516efa9ae02",
				"version": "2.27.1"
			},
			"value": [1625181149.085, "1"]
		}]
	}
}
```

In the response we see a single result (not duplicated). So I'm not sure what is different in your setup but it should do the deduping assuming the labels on the timeseries match.

**Comment by ravibhooshan** [comment]
thanks for confirming @jacksontj.
I am going to check again, my config is similar to what you shared.
I am not sure if issue is with the version of promxy I am using. I pulled docker image from /alterway/promxy

**Comment by jacksontj** [comment]
From a quick look that fork is pretty out-of-date (no updates since May 2020); so I'd suggest running on mainline. 

I'm going to assume that the issue has been resolved (since no update in a few weeks); if this is still an issue please feel free to re-open!
