### ISSUE TITLE
Proposal: Show targets of all prometheus servers in targets tab.

### ISSUE THREAD

**Issue by zbindenren** [jacksontj/promxy#446]
Currently this tab is empty. It would be great to see all targets of all prometheus servers.

**Comment by jacksontj** [comment]
This has been asked previously in https://github.com/jacksontj/promxy/issues/369#issuecomment-760647884. TLDR; this targets page doesn't use the standard prom API and instead uses the scrape target manager -- which promxy doesn't use. So making this page show the downstream prom servers would be pretty difficult; I could pretty easily make this page 404 instead?

**Comment by zbindenren** [comment]
Thx for the answer. Wouldn't it be possible to start a go routine which scrapes all prometheus targets and return it under /api/targets?

**Comment by jacksontj** [comment]
Promxy doesn't scrape metrics and as such we can't "just scrape" prometheus targets. Unfortunately since the UI page is tied to the scrape side I can't really make that work without some serious changes to the upstream prom code (which I'm not really seeing the ROI on). As I mentioned before I can definitely make it 404 (probably "clearer" since this doesn't work and likely won't ever work).

**Comment by zbindenren** [comment]
Just for clarification: I dont mean it should scrape metrics, just make periodically an api call to /api/targets for each configured prometheus server. Then just display the results in the targets page.

**Comment by jacksontj** [comment]
The problem with this is the interfacing. The prometheus code that generates that targets page takes in the structs that actually do the scraping. So to have it generate the page we'd have to instantiate all the scrapers etc. (which is a mess in itself -- let alone in such a way to combine downstreams and not scrape). This is unfortunate as the rest of the APIs are generally UI split from API so the API endpoint is easy to override (this has the 2 combined into a single HTML endpoint).
