### ISSUE TITLE
Support for function last_over_time

### ISSUE THREAD

**Issue by varuzam** [jacksontj/promxy#447]
Currently promxy returns the error
```parse error: unknown function with name "last_over_time"```

Pormetheus supports that - https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time

**Comment by kali-brandwatch** [comment]
+1

**Comment by kali-brandwatch** [comment]
Aliaksandr Valialkin from Victoria Metrics said the following:
```
I believe the support for last_over_time() can be added to promxy by updating the dependency on Prometheus package there. 
```

**Comment by jacksontj** [comment]
This should be added with #460
