### ISSUE TITLE
Querying exemplars API Error

### ISSUE THREAD

**Issue by briskjj** [jacksontj/promxy#453]
Querying exemplars
This is experimental and might change in the future. The following endpoint returns a list of exemplars for a valid PromQL query for a specific time range:

GET /api/v1/query_exemplars
POST /api/v1/query_exemplars

https://prometheus.io/docs/prometheus/latest/querying/api/

Grafana integrates this interface now ，some page returns ‘404 Not Found’，Will Promxy be compatible in the future?

**Comment by jacksontj** [comment]
As of today promxy doesn't support exemplars; There is already an issue open (#420) for adding the functionality -- so I'll close this one as a duplicate.
