### ISSUE TITLE
Not able to see all the metrics

### ISSUE THREAD

**Issue by jnsrikanth** [jacksontj/promxy#455]
Hi,
I am using the helm chart for Promxy given here and have deployed it into my AKS Kubernetes with 20 Nodes. I am able to configure the promxy datasource in Grafana. Also I have a 3 replicas and 2 shards architecture in Prometheus deployed using the latest (August 2021) operator helm chart.

The link for the promxy helm repo: 
[Promxy Helm Chart](https://github.com/AnchorFree/helm-charts/tree/master/stable/promxy
)

While I am able to see most of the metrics related to the standard Kubernetes Node Exporter in Grafana dashboard, however I am not able to see all the metrics related to persistent volumes, statefulsets, deployments etc. What additional configuration need to be added to ServerGroup in promxy configuration? in order to retrieve metrics for all the targets in my K8S environment?

Also do I need to create a custom ClusterRole and ClusterRoleBinding with a Service Account in order for Promxy to get everything in Grafana?

Please help.

**Comment by jacksontj** [comment]
>  however I am not able to see all the metrics related to persistent volumes, statefulsets, deployments etc. 

Promxy doesn't scrape any metrics; so this would be a question somewhere between the exporters (e.g. KubeStateMetrics) and prometheus (the thing that scrapes).

> What additional configuration need to be added to ServerGroup in promxy configuration?

Promxy is just an aggregating proxy; so it should be pointing at your prometheus hosts in servergroups based on their configuration.

> Also do I need to create a custom ClusterRole and ClusterRoleBinding with a Service Account in order for Promxy to get everything in Grafana?

This shouldn't be necessary as promxy doesn't scrape any data. Now I would expect that those exporters will require some specific perms (e.g. KubeStateMetrics) but those should be covered in the examples from the various exporters.
