### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by Makkinwa** [jacksontj/promxy#457]
I've got this error when starting promxy:

level=info ts=2021-09-02T15:46:54.304Z caller=kubernetes.go:264 discovery=kubernetes msg="Using pod service account via in-cluster config"
panic: WHAT

goroutine 1 [running]:
github.com/jacksontj/promxy/pkg/proxystorage.(*ProxyStorage).ApplyConfig(0xc00011fac0, 0xc00004e960, 0xc00004e960, 0x0)
	/go/src/github.com/jacksontj/promxy/pkg/proxystorage/proxy.go:122 +0x6fa
main.reloadConfig(0xc0003f8318, 0xc0000ac880, 0x5, 0x8, 0x8, 0x30ff3c0)
	/go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:117 +0xb4
main.main()
	/go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:383 +0x189c

I don't really understand what is wrong and why I'm getting it
panic: WHAT does not say a lot 

My promxy config: 
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy
    remote_write:
      - url: http://172.17.148.169:8083/receive
    promxy:
      server_groups:
      - kubernetes_sd_configs:
        - role: pod
      - static_configs:
        - targets:
          - 172.17.255.29:9090
I launch promxy in K8s cloud btw
Can you help me out on this?

**Comment by jacksontj** [comment]
You seem to be running a somewhat old version as that panic was removed in d08e35c24025d819afff84808f7f73c1afdde847 (part of v0.0.67), could you try upgrading to latest and see if you get any errors?

**Comment by jacksontj** [comment]
Since there has been no update in a week I'll assume this is resolved. If thats not the case please feel free to re-open!

**Comment by danksim** [comment]
I am also running into this problem using the latest image from quay.io
