### ISSUE TITLE
Need understanding on promxy dashboard

### ISSUE THREAD

**Issue by raonelakurti** [jacksontj/promxy#487]
I have gone through Promxy dashboard to find out the prometheus query latency

```
"expr": "sum(rate(prometheus_engine_query_duration_seconds_sum{job=\"promxy\"}[1m])) by (slice)\r\n/\r\nsum(rate(prometheus_engine_query_duration_seconds_count{job=\"promxy\"}[1m])) by (slice)",
```

@jacksontj   What is the job="promxy" is that a variable ?

**Comment by jacksontj** [comment]
`job="promxy"` is a way to scope the metrics to just promxy (as opposed to prometheus as well). The "norm" in prometheus is to have a label `job` which is the scrape job name. So if you have a different value other than promxy it'd need to change.

**Comment by raonelakurti** [comment]
@jacksontj  We have a 3 Prometheus clusters and we have Promxy on top it to do aggregation. How do we calculate query latency to Individual prometheus servers. Am I referring the right query and dashboard?

**Comment by raonelakurti** [comment]
@jacksontj I still didn't understand where to check job=promxy?

When I checked metrics in promxy(On the backend we have 3 prometheus clusters)

```
server_group_request_duration_seconds_sum{call="label_values",host="prometheus.monitoring.west.net",status="success"} 3.5157698900000014
server_group_request_duration_seconds_count{call="label_values",host="prometheus.monitoring.west.net",status="success"} 51
server_group_request_duration_seconds_sum{call="label_values",host="prometheus.monitoring.west.net",status="success"} 4.142353209
server_group_request_duration_seconds_count{call="label_values",host="prometheus.monitoring.west.net",status="success"} 51
server_group_request_duration_seconds_sum{call="label_values",host="prometheus.monitoring.east.net",status="error"} 0.151442344
server_group_request_duration_seconds_count{call="label_values",host="prometheus.monitoring.east.net",status="error"} 2
server_group_request_duration_seconds_sum{call="label_values",host="prometheus.monitoring.east.net",status="success"} 2.008951508
server_group_request_duration_seconds_count{call="label_values",host="prometheus.monitoring.east.net",status="success"} 49
server_group_request_duration_seconds_sum{call="label_values",host="prometheus.monitoring.south.net",status="success"} 3.1061237509999997
server_group_request_duration_seconds_count{call="label_values",host="prometheus.monitoring.south.net",status="success"} 51
```

I'm looking for a query dashboards to find out latency

**Comment by jacksontj** [comment]
if you do something like `sum(rate(server_group_request_duration_seconds_sum[1m])) / sum(rate(server_group_request_duration_seconds_count[1m]))` that should get you average latency

**Comment by jacksontj** [comment]
Given no updates in ~2 weeks I'm going to go ahead and close this question out -- if you have further questions feel free to re-open or create a new issue.
