### ISSUE TITLE
Feature request: server group hint

### ISSUE THREAD

**Issue by computerphilosopher** [jacksontj/promxy#488]
In many cases, users classify the Prometheus instances by labels. we can use labels to determine the right query target. 
for example: external label, job label, instance label  

If we can give a query hint to the promxy, we can save the cost of the 'scatter and gather' operation.

we may refer 'match' property of the federation feature.

https://prometheus.io/docs/prometheus/latest/federation/

**Comment by jacksontj** [comment]
So it sounds like you are wanting promxy to only route requests to the servergroups that *could* have data (based on labels etc.). If so this functionality already exists! As an example, if you have a label configured (e.g. az=uswest1a) then queries with that label set will be routed appropriately. So if you were to (as an example) query for `foo{az="uswest1a"}` promxy will only send to that specific servergroup.

Hopefully that answers the question?

**Comment by computerphilosopher** [comment]
Thank you for answer. it helped so much. Our team is considering to choice the promxy to alternative of the Thanos.
