### ISSUE TITLE
repeat absent()'s function behaviour as Thanos query does

### ISSUE THREAD

**Issue by Vladikamira** [jacksontj/promxy#496]
Hi 👋 
By query like this one
```
absent(up{dc="1"}) != 0
```
when we have Prometheuses (HA setup) running with external_labels like `dc=1` and `dc=2` per cluster, we can check wether all metrics from `dc=1` are missing or not. It works for Thanos + Prometheus, but not for Promxy + Prometheus. 
I believe that's because of the difference on how Thanos and Promxy works:

- Thanos rely on remote_read API and fetch all raw data from all clusters, and only then apply `absent` function, which checks over all fetched data
- Promxy rely on Prometheus query API and just summaries responses from backends (clusters), where each of them will takes care of function evaluation separately

For instance, There are two clusters `dc=1` and `dc=2`. If I would  like to check wether cluster `dc=2` is alive or not, then for  a query `absent(up{dc="2"})` I will get (if all clusters are alive):

In case of Thanos
```
no data
```
as there are metrics within `absent()` function

In case of Promxy
```
{dc=1}  1
```
as `dc=2` cluster processed query properly and returned `empty` response, but `dc=1` returned `{dc=1}  1`, so Promxy just stitched responses.

So, at first I would like to make sure that my understanding of how `absent` function processed by Promxy is correct 😅 
If it's correct, is it possible to implement some post processing on Promxy layer for such cases to repeat Thanos behaviour?

P.s. I know that it can be replaced by `count` instead 
```
count(up{dc="2"}) != 0
```
just want to make migration from Thanos to Promxy easier :) as there are many alerts configured inspired by [this article](https://www.robustperception.io/absent-alerting-for-jobs)

**Comment by hanjm** [comment]
i am face same issue when merge two datasource. absent(any_metric) always return 1 if one of datasource not have this metric. expect return 1 if all datasource not have this metric.
