### ISSUE TITLE
The result of the max_over_time is different from the expectation

### ISSUE THREAD

**Issue by computerphilosopher** [jacksontj/promxy#502]
The result of the max_over_time is different from the expectation

1. My applications switch their role every 5 minutes. they have different metrics set by role. so some metrics appears during the first 5 minutes, and do not appear during the following 5 minutes.

2. The dashboard use 'max_over_time' function to catch spikes. (reference: https://cloudinfrastack.com/blog/monitoring/using_prometheus_subquery_for_capturing_spikes/)

If I query to the Prometheus directly or query to the Promxy without aggregation, the data pattern is normal. 
![image](https://user-images.githubusercontent.com/26251856/155098765-0cdad0c5-5d36-4fdd-8e38-6d96f6d2935e.png)

But if I query Promxy with aggregation, data pattern is abnormal. the graph is continued all time.

![image](https://user-images.githubusercontent.com/26251856/155098825-d65b8418-4049-4f2c-b480-5afe2498e654.png)

**Comment by jacksontj** [comment]
My initial guess here is that this is another case of lookback delta causing issues (e.g. https://github.com/jacksontj/promxy/issues/519#issuecomment-1200348580). Could you attempt the same with a short (or 0) lookback delta on promxy?

If that doesn't resolve it if you could provide a pcap or the trace logs that should help debug this further.

**Comment by computerphilosopher** [comment]
@jacksontj 

Thank you for your answer. But I resigned from a job this June. So I don't have access permission to that dashboard. I will try to reproduce a problem using another metric set. But I can't be sure reproducing is possible.
