### ISSUE TITLE
PromXy giving OOM and restarts 

### ISSUE THREAD

**Issue by skdas2016** [jacksontj/promxy#503]
The promxy pods running in EKS .. with HPA in place with min 5 pods.
Memory 8GB/16GB , concurrency 50 . NoCache . Against VictoriaMetrics data 
most of the queries and under 1 sec .. and mostly less data in response 
Most of the time memory is 5-8GB but when sudden spike in query volume increase memory grows up to 16GB with few seconds and restarts happens ….

Using v.70+ versions  

trying to know what are the possible reasons ? 
1- high volume of requests ? 
2- low concurrency of 50 ? 
3- Memory not getting released or garbage collection not happening ? 

Also not seeing any detailed documents related to how promxy works behind the screen ..share a link if there is one ..

thanks in advance

**Comment by skdas2016** [comment]
Trying see some replies or updates on this ... Can someone help ?

**Comment by skdas2016** [comment]
Hi Team ,
Any valuable feedbacks on this issue ?

**Comment by jacksontj** [comment]
Its been a few months on this issue, so I'm going to go ahead and close this out. If you are still experiencing the issue please feel free to re-open the issue.
