### ISSUE TITLE
Utilization of cache with VictoriaMetrics

### ISSUE THREAD

**Issue by xenofree** [jacksontj/promxy#504]
We have two instance of VictoriaMetrics deployed and querying them with promxy.
We have to enforce no_cache=1 for this to work.

Is it possible to cache query with promxy ?

**Comment by nemobis** [comment]
> Is it possible to cache query with promxy ?

Is your question answered by https://github.com/jacksontj/promxy/issues/41 ?

**Comment by jacksontj** [comment]
It is unlikely that we'd be able to use the VM caching -- more detail can be found in the initial issue discussion https://github.com/jacksontj/promxy/issues/202

TLDR; VM caching returns the wrong timestamp (in an attempt for efficiency) which the promql engine doesn't like.
