### ISSUE TITLE
No result when using relative time_range

### ISSUE THREAD

**Issue by sharkpc0813** [jacksontj/promxy#506]
Hello.
I'm trying to aggregate longterm series and shortterm series with promxy.
The query result of shortterm is not shown if it exceeds the range set in `relative_time_range`.

![스크린샷 2022-03-28 오후 3 55 18](https://user-images.githubusercontent.com/6148396/160343428-12ac4bb6-0c46-4f5c-aa82-ad438ebce054.png)

I set `relative_time_range` as follows.

#### promxy
```
// server group shortterm
relative_time_range:
  start: -480h
  end: 0
  truncate: true

// server group longterm
relative_time_range:
  start: -8000h
  end: -480h
  truncate: true
```

#### victoria-metrics
```
// shortterm
- scrape interval : 10s
- args of victoria-metrics :
        - -retentionPeriod=20d
        - -promscrape.config=/config/prometheus.yml
        - -promscrape.configCheckInterval=30s
        - -search.maxLookback=20s
        - -storageDataPath=/storage
        - -httpListenAddr=:80
        - -search.logSlowQueryDuration=60s
        - -search.maxPointsPerTimeseries=1000000
        - -search.maxQueryDuration=180s
        - -search.maxQueryLen=1638400
        - -search.minStalenessInterval=20s
        - -promscrape.maxScrapeSize=150MiB
        - -maxLabelsPerTimeseries=50

// longterm
- scrape interval : 1h
- args of victoria-metrics :
        - -retentionPeriod=365d
        - -promscrape.config=/config/prometheus.yml
        - -promscrape.configCheckInterval=30s
        - -search.maxLookback=2h
        - -storageDataPath=/storage
        - -httpListenAddr=:80
        - -search.logSlowQueryDuration=60s
        - -search.maxPointsPerTimeseries=1000000
        - -search.maxQueryDuration=180s
        - -search.maxQueryLen=1638400
        - -search.minStalenessInterval=2h
        - -promscrape.maxScrapeSize=150MiB
        - -maxLabelsPerTimeseries=50
```

When I debugged, query results are returned from each victoria-metrics, but there seems to be a problem when aggregating in promxy.
  - In [prometheus engine codes](https://github.com/prometheus/prometheus/blob/a64b9fe323cf913c212c1829fe93d1a9dbc63348/promql/engine.go#L1715), if the reftime and the timestamp of the sample match, the query result is displayed.
  - In this case, the longtterm has a matching timestamp, but the shotterm doesn't have a matching timestamp, so it looks like there is no query results for shortterm.

Probably because the two victoria metrics are collected at different scrape intervals, so they have samples at different steps and lookback-delta.

Any ideas on how to solve this case?

--- 

I think it would be nice to add a fillter that decides which `server_group` to query according to the time range for scrapers with different scraping configs.
(e.g. query_range(7d) -> returns from shotterm server_group; query_range(30d) -> returns from longterm server_group)
If it's okay, I'll make a pull requests.

**Comment by jacksontj** [comment]
This definitely seems like a unique use-case. Given that your issue is with the "shortterm" metrics missing, maybe its some sort of caching issue in VM (https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L54). If that doesn't solve it we'd require some more debugging. So ideally a repro case -- but if not a pcap or trace logs should be sufficient.

**Comment by jacksontj** [comment]
As its been a while with no updates I'll go ahead and close this out (as it will require some more data to dig in); if you have some additional data or repro-cases please feel free to re-open this case!
