### ISSUE TITLE
Loki support

### ISSUE THREAD

**Issue by github-vincent-miszczak** [jacksontj/promxy#512]
Hi,

We already use Promxy to make multiple Cortex clusters spread over multiple regions appear as one datasource in Grafana, works great.
We now have the same use case for Grafana/Loki, and could not find an equivalent software to aggregate multiple clusters to query logs.

Do you think Promxy would be a good candidate for such feature or should we start a new project from scratch? (or use another software we missed)

**Comment by jacksontj** [comment]
I'm not very familiar with the API specifics for Loki, Given that it is log-focused instead of timeseries focused some of the logic in promxy is unnecessary (e.g. stitching series, etc.). As such it may make sense to have it as a separate binary or a separate project (depending on API similarities etc.). But I'm not opposed to putting it into this project if someone has interest in helping knock out a version.

**Comment by nachopv** [comment]
Hi @jacksontj 

In Loki we do have 3 use cases

**[Log queries](https://grafana.com/docs/loki/latest/query/log_queries/)**

You are rigth that in this case there is no much added value appart from merging 2 set of logs

`{projectkey="foo",environment="dev"}`

**[Metrics queries ](https://grafana.com/docs/loki/latest/query/metric_queries/)**

From grafana documentation ... _Metric queries extend log queries by applying a function to log query results. This powerful feature creates metrics from logs._

I think this is the use case  that @github-vincent-miszczak  was pretty much thinking of. Once you start applying aggregation functions I would say you are more likely working already on prometheus than on Loki so there's a lot of logic on promxy that could be reused in this use case

`sum(count-_over_time({projectkey="foo",environment="dev"}[1m])) by (tenant)`

Label values

This use case is identical than the prometheus one so could easily fit too

We are interested in this extension and you think it makes sense  we are open to contribute to the project

**Comment by jacksontj** [comment]
Definitely an interesting idea. I'd be curious to see how much "fits" in promxy vs as a library dependency -- but definitely not opposed to contributions for loki into the promxy project (as it does sound related).
