### ISSUE TITLE
Is the project still being maintained?

### ISSUE THREAD

**Issue by dudicoco** [jacksontj/promxy#518]
Hi,

The last release for promxy was over half a year ago, is the project actively maintained?

Currently i'm using Thanos to dedup metrics, I like the idea of not having to use sidecars, however Thanos has a much bigger community and is actively maintained.

Perhaps it would be reasonable to merge this project into Thanos and introduce some of its feature there?

Thanks

**Comment by jacksontj** [comment]
This project is still maintained and I'm aware of a few places that are actively using it. Features etc. have been a bit slower as (1) it works pretty well and (2) there haven't been a lot of other contributors -- so its just me in my spare time.

I did pitch putting this in both the Prometheus project and Thanos project previously and there was no interest (some where quite against the idea). As such I'm more than happy to maintain this here. In addition, if you have fixes/features/etc. I'm more than happy to help guide new contributors :)
