### ISSUE TITLE
Queries fail immediately when all targets in one group are down

### ISSUE THREAD

**Issue by nemobis** [jacksontj/promxy#521]
I have Promxy set up with two server groups, each containing two VictoriaMetrics targets. One goal of this setup is that the user doesn't need to know which of the target groups contains the data they're looking for; the other is that for some metrics it's possible to provide some redundancy across both groups.

However, Promxy seems to effectively go down if all targets in a group go down: all queries fail immediately. A grafana dashboard will fail to load even if it doesn't need any data from the unavailable group. This feels unnecessary.

The culprit might be the `requiredCount` in MultiAPI, which is designed to fail as early as possible:
```go
				// If there aren't enough outstanding requests to possibly succeed, no reason to wait
				if (outstandingRequests[ret.ls] + successMap[ret.ls]) < m.requiredCount {
					return nil, warnings.Warnings(), ret.err
				}
```
and
```go
	// Verify that we hit the requiredCount for all of the buckets
	for k := range outstandingRequests {
		if successMap[k] < m.requiredCount {
			return nil, warnings.Warnings(), errors.Wrap(lastError, "Unable to fetch from downstream servers")
		}
	}
```

It would be nice to be able to configure this requiredCount, or to otherwise influence this behaviour.

Otherwise, if one is supposed to use a single server group for two groups of targets, where one group is designed to be a (partial) fallback for the other group, maybe this could be addressed somewhere in the docs, for instance after the line in the README:

> A ServerGroup is a set of prometheus hosts configured the same.

**Comment by nemobis** [comment]
https://github.com/jacksontj/promxy/issues/3 is sort of related.

**Comment by jacksontj** [comment]
Thanks for reaching out!

From reading over your issue it sounds like there may just be some misunderstanding/miscommunication around the servergroups.

So as you quoted a servergroup is a set of prometheus hosts that are configured the same. So based on your description of 2 servergroups with 2 targets each, I expect you have 4 total VM nodes:

- SG1 - VM1
- - SG1 - VM1
- - SG1 - VM1

**Comment by nemobis** [comment]
>  So based on your description of 2 servergroups with 2 targets each, I expect you have 4 total VM nodes:

Yes, I do. If 2 are down, I still want the results from the other 2.

**Comment by jacksontj** [comment]
@nemobis sorry, I mis-sent before -- I just finished editing the comment with the rest of the context :)

**Comment by nemobis** [comment]
> to ensure we aren't missing data

Understandable, but I'm not sure that's an improvement. I'll try to ignore errors!

**Comment by jacksontj** [comment]
Yea, its a bit of a philisophical question. In the event of "plain" data fetching missing data is maybe okay -- but if you are relying on this for alerting you get a false sense of security. For example, if the alert was based on error rate, and a bunch of nodes were missing metrics (because of an SG missing) you'd have an alert green (because it was missing the data) instead of red (because it was unable to fetch).

Given that context my decision was to have promxy err on the side of visibility here (since it is effectively an error fetching data). So I definitely caution against the use of ignore_error -- but in some use-cases that is the desired behavior.

**Comment by nemobis** [comment]
Indeed, for alerting it would be a big problem. (Or any automatic consumer really.) We've not dared to use promxy for alerting yet.
