### ISSUE TITLE
Support /api/v1/targets/metadata for help text tooltip in Grafana

### ISSUE THREAD

**Issue by nemobis** [jacksontj/promxy#526]
Since Grafana 8.5 (https://github.com/grafana/grafana/pull/46163), the Grafana query builder provides the help text of a Prometheus metric in a tooltip when autocompleting a metric name. This appears to rely on data from [/api/v1/targets/metadata](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-target-metadata).

My Prometheus instance at `/api/v1/targets/metadata?metric=node_memory_MemTotal_bytes` returns a number of timeseries, each with a `help` field. On Promxy, at the same path I get only `{"status":"success","data":[]}`.

If Promxy could be used directly, this would make it easier for people to use the Grafana explore tab and the dashboard editor to write queries. My current workaround is to use a Prometheus endpoint while I'm testing queries, and only afterwards switch to querying through Promxy.

**Comment by xujiaxj** [comment]
Do you mean `api/v1/metadata` metric metadata API used by Grafana? I think the `targets/metadata` is the target metadata API and is not used by Grafana.

**Comment by nemobis** [comment]
Il 17/01/23 22:04, Jia Xu ha scritto:
> Do you mean `api/v1/metadata` metric metadata API used by Grafana?

Probably yes, sorry for the confusion.

**Comment by petemounce** [comment]
Something similar sounding to this happens for [promlens](https://github.com/prometheus/promlens) 0.3.0:

promlens querying prometheus - metadata is present:
![Screenshot 2023-08-24 at 10 44 00](https://github.com/jacksontj/promxy/assets/69720/e33506df-63c9-40a6-a471-bbcdacf24c0f)

promlens querying promxy (same prometheus backend as above) - metadata is missing:
![Screenshot 2023-08-24 at 10 40 55](https://github.com/jacksontj/promxy/assets/69720/b0d57a06-f84e-4b5c-ae9b-804b8eef0d07)
