### ISSUE TITLE
Invalid startDate is passed

### ISSUE THREAD

**Issue by dupondje** [jacksontj/promxy#528]
We started using Promxy to aggregate metrics from Thanos and VictoriaMetrics.
This works fine, except that we have issues with /series call's without a start/end timestamp included.

```
DEBU[2022-12-21T13:25:04+01:00] http://xxx:8428                        api=Series endTime="292277025-08-18 07:12:54.999 +0000 UTC" matches="[{tag=\"Y1\",__name__=\"system_uptime\"}]" startTime="-292273086-05-16 16:47:06 +0000 UTC"
DEBU[2022-12-21T13:25:04+01:00] http://xxx:10912                       api=Series endTime="292277025-08-18 07:12:54.999 +0000 UTC" matches="[{tag=\"Y1\",__name__=\"system_uptime\"}]" startTime="-292273086-05-16 16:47:06 +0000 UTC" took="299.112µs"
DEBU[2022-12-21T13:25:04+01:00] http://xxx:8428                        api=Series endTime="292277025-08-18 07:12:54.999 +0000 UTC" matches="[{tag=\"Y1\",__name__=\"system_uptime\"}]" startTime="-292273086-05-16 16:47:06 +0000 UTC" took=4.870023ms
DEBU[2022-12-21T13:25:04+01:00] Select                                        matchers="[tag=\"Y1\" __name__=\"system_uptime\"]" selectHints="&{-9223309901257974000 9223309901257974999 0 series [] false 0}" took=5.035425ms
XXXXX - - [21/Dec/2022 12:25:04] "POST /api/v1/series HTTP/1.1 200 30" 0.005280 match%5B%5D=system_uptime%7Btag%3D%22Y1%22%7D
```

As you see it passes  startTime="-292273086-05-16 16:47:06 +0000 UTC" to the backend, which seems to be unable to parse this and returns no results.
When passing start=1 (0 doesn't work neither) to the /series call, then you get results. But without specifying a start value, it returns an emply resultset.

**Comment by jacksontj** [comment]
Unfortunately this is an upstream client_golang bug (https://github.com/prometheus/client_golang/issues/621) -- TLDR the client requires a `time.Time` and will format it regardless of the value. I had proposed a fix upstream but that seemed to stall out. So unfortunately until that is fixed upstream there is little to do here (short of forking that client).
