### ISSUE TITLE
"use --enable-feature=" errors

### ISSUE THREAD

**Issue by WojciechKuk** [jacksontj/promxy#532]
some of promQL queries (via promxy) end up with errors like this:

`
bad_data: negative offset is disabled, use --enable-feature=promql-negative-offset to enable it
`

`
bad_data: @ modifier is disabled, use --enable-feature=promql-at-modifier to enable it
`

On backends (victoriametrics & prometheus), we can use negative offsets and "at" modifiers, so the source of these errors is promxy.

How can I enable those functionalities on **promxy**? 
I can't find related commandline parameters, and even I can't find related code in promxy source code.

**Comment by WojciechKuk** [comment]
similar functionality in thanos: https://github.com/thanos-io/thanos/pull/4026/files

**Comment by jacksontj** [comment]
This is a duplicate of  #479
