### ISSUE TITLE
help, how to drop 'prometheus' label on different servergroup?

### ISSUE THREAD

**Issue by gotosre** [jacksontj/promxy#534]
help, how to drop 'prometheus' label on different servergroup?

**Comment by gotosre** [comment]
desc:
two ups:
- thanos with label prometheus: thanos
- victoriametrics with label prometheus: vm

promxy in front of them to uniform entry

how to remove prometheus label ,when query via promxy? any config?

**Comment by jacksontj** [comment]
This appears to be a duplicate of #258 ?
