### ISSUE TITLE
feature: metrics filtering based on `__name__` label (whitelisting)

### ISSUE THREAD

**Issue by Vladikamira** [jacksontj/promxy#558]
Hey, 
We are using `promxy` as a glue to stitch multiple clusters and layers of VictoriaMetrics without our organization and it works just great! Recently we started onboarding other PromQL API-compatible endpoints and connecting them as leaves on the lower layers. 
For instance, we onboarded [GCP metrics endpoint](https://cloud.google.com/stackdriver/docs/managed-prometheus/promql) so now we can alert on that and make awesome graphs in Grafana. 
The problem is, that we have all queries even not related to GCP metrics passing over GCP API which is not free, and we are billed by the number of API calls. 
What do you think would be the best approach to protect this endpoint from requests that not belongs to it?

We came up with the [idea](https://github.com/Vladikamira/promxy/blob/metricsfilter/cmd/promxy/config.yaml#L32) to implement filtering within `promxy` with pulling all `__name__` labels from upstream server groups and [allow](https://github.com/Vladikamira/promxy/blob/metricsfilter/pkg/proxystorage/proxy.go#L257) only expressions with these metric names. In addition, there is an option to include/exclude some names statically.
Again, I'm not sure what would be the best approach here - maybe we should implement a separate proxy as a sidecar to filter out such requests instead of having it as part of `promxy` 🤷‍♂️  
wdyt?

**Comment by jacksontj** [comment]
This is an interesting feature request (so far most uses are against prometheus/VM boxes that people own; so reducing call count isn't a major concern).

I think the top-level idea is okay (filtering the requests at the client) but I would implement it slightly differently. I initially planned to just write it out, but i found it easier to hack up a version to talk through it (https://github.com/jacksontj/promxy/pull/560)

So practically something like this seems to work quite well at reducing the calls downstream, the only config I'd see in this setup is just a list of labels to maintain the filter on (https://github.com/jacksontj/promxy/pull/560/files#diff-e600914128deddf0a5af9d220cccd92dd82f0daf65301fbbd4731f966937755bR17).

The main concerns I have with this are around the scale of this. If the downstream is massive the data here can get fairly large (in one large cast the result of LabelValues for `__name__` is ~2MB -- so large but probably manageable. This could pretty easily pick some label with SUPER high cardinality and break things too -- so a tough balance to walk.


I think the config would end up looking something like:

```
label_filter:
  # which labels to maintain a sync for
  labels_to_filter: ['__name__', 'job']
  # how often to sync from the downstream
  sync_interval: 5m
```

And if the dataset gets too large we could add the ability to store that list on-disk -- but practically probably more effort than its worth. IMO if you have static labels that can be covered with the `labels` config -- so  this fully dynamic approach adds this dynamic filtering approach.


Hopefully that makes some sense, any thoughts/input?

**Comment by jacksontj** [comment]
FYI I have updated the PR with tests, background async, and the exclude option. So really just need an understanding of the goal behind the `include` option -- then I think we're good to go :)

**Comment by Vladikamira** [comment]
btw, would be possible to add a metrics counter for amount of blocked/declined requests by label filter?
something like: `promxy_label_filter_requests_declined_total` 🤔

**Comment by jacksontj** [comment]
> For instance, if you need to give access to some specific metrics to someone outside of your company, then we could limit it by one Promxy deployment as an entry point to those metrics.

I can add the include list in -- but this wouldn't be a secure way of providing that functionality -- as they could get around by not including that matcher. For example; if the metric you are trying to restrict them from is `foo{a="b"}` and you restricted `foo` they could just query `{a="b"}` and still get it. I'm still going to include this, as for your initial case this may be a better approach -- since you could administratively pull the list of labels and put it in config -- instead of having it dynamically pulled each startup/reload.

> would it be possible to add a metrics counter for amount of blocked/declined requests by label filter?

Trivially so, added :)
