### ISSUE TITLE
Limit queries to server groups by using label?

### ISSUE THREAD

**Issue by dgrizzanti** [jacksontj/promxy#57]
Hi,

First off - great project. Looking forward to making use of it.

I had a question regarding a (potential) improvement to the scatter gather logic for queries. I know there is currently an issue  (#2) open in regards to reducing the querying to only those server groups that have a given set of metrics. However, I was curious if you'd given any thought to reducing the queries by the labels provided in the promql statement prior to issuing a query to all server groups.

That is, if I had a promql statement that looked like this:
`http_server_200{sg="localhost_9090"}`

Only send that query to server groups with the matching label. Maybe this is naive and ignoring the existing implementation but just curious if this was something you'd considered.

Thanks!

**Comment by jacksontj** [comment]
This is actually something I have considered and implemented more recently. In the config you define the [`labels` section ](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L31) which adds labels to those metrics. In addition to just adding the labels to the metrics, they are used for routing as well. So if you want to filter based on those in your promql it will only target servergroups that would match.

The plans for #2 are basically to reduce this even further as in reality metrics usually live in a subset of the servergroups, and ideally the promql users shouldn't need to keep too much track of *where* the metrics are, just that they know which ones they want.

**Comment by dgrizzanti** [comment]
Oh, awesome. I think that feature alone with be useful for narrowing down queries to only certain server groups. Answers my question so feel free to close this!

**Comment by jacksontj** [comment]
Thanks for the question! Let me know if you have any other questions/comments/concerns -- and I hope promxy can be helpful to you too :)

**Comment by raffraffraff** [comment]
Sorry for commenting on a closed issue but in PR #37 you are _adding_ a new label and filtering on it. What if the label I want to filter on already exists on my metrics? For example, I have a bunch of different datacenters, and the Prometheus servers in each datacenter already add a 'dc' label. All of my Grafana dashboards have 'dc' variables and filters. But I can't use that. Defining 'dc' as a label in Promxy has no effect on filtering, and all requests go to all datacenters. "Am I doing it wrong?"
