### ISSUE TITLE
question: log levels

### ISSUE THREAD

**Issue by palmerabollo** [jacksontj/promxy#59]
I am not able to control the log level.

I've tried running promxy v0.0.18 with different `--log-level` values (debug, info, warn). For example I always see requests that shouldn't appear with `--log-level=warn`:

```
[28/Jul/2018 07:51:59] "GET /-/healthy HTTP/1.1 200 23" 0.000015
[28/Jul/2018 07:52:00] "GET /metrics HTTP/1.1 200 5156" 0.083476
[28/Jul/2018 07:52:00] "GET /-/healthy HTTP/1.1 200 23" 0.000015
```

What are the supported `--log-level` values?
Thank you!

**Comment by jacksontj** [comment]
Thanks for reporting the issue!

The log-levels work as you'd expect, the one "gotcha" is that the access logging (the lines that you pasted) aren't currently going through the logging handlers (they are writing directly to stdout). Access logs aren't really the "same" as other logs, so I'm still not 100% sure what I want to do there. Likely add some options to control it going somewhere direct (a file, stdout, etc.). Input is definitely welcome :)


So to circle back to the original issue `I am not able to control the log level.` you should be able to make some *more* lines appear using the `debug` log level, but as of now you cannot get rid of those access log messages (as described above).

**Comment by palmerabollo** [comment]
I understand. I think that adding an additional option to control where to send them would introduce some undesired complexity in docker-based scenarios, where writing everything to stdout and letting other process gather logs is a common practice.

What do you think about sending the logs to the same logging handlers (in debug level) + adding an option to the app to send the logs to a file for those who need it? Too tricky?

**Comment by jacksontj** [comment]
I've opened up #77 which adds a CLI flag for this. The default sticks with stdout, but it has options for:
- stdout
- stderr
- none
