### ISSUE TITLE
Promxy Auth in VictoriaMetrics

### ISSUE THREAD

**Issue by Antilles7227** [jacksontj/promxy#598]
We need to place VictoriaMetrics instance behind Promxy. That VM instance have auth on remote read uri. How to propagate user:pass to promxy config, so it can authenticate requests?

**Comment by jacksontj** [comment]
Promxy has a flag for `ProxyHeaders` (https://github.com/jacksontj/promxy/blob/master/cmd/promxy/main.go#L88) to pass down headers sent to promxy to the downstream servergroups.

**Comment by jacksontj** [comment]
At this point it seems that the question is answered, if you have additional questions please feel free to re-open!
