### ISSUE TITLE
Native histogram support

### ISSUE THREAD

**Issue by jmcarp** [jacksontj/promxy#601]
This is a question and possibly a feature request: does promxy support prometheus native histograms? Would we need to update the vendored prometheus fork for this to work?

**Comment by jacksontj** [comment]
Short answer, yes.

Longer answer:  Histograms are actually more-or-less calculated query side (https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile). So this (under the hood) is the same as all of the other servergroup merging.

**Comment by jmcarp** [comment]
Thanks!
