### ISSUE TITLE
Log Query Promxy

### ISSUE THREAD

**Issue by juliocleal14** [jacksontj/promxy#653]
Hi folks, how are you?

In the Prometheus, we have a possibility to enable the [log query](https://prometheus.io/docs/guides/query-log/) to store logs executed and debug possible problems.

Is there a way to enable some similar in the Promxy?
Or maybe enable tracing?

Thank you!

**Comment by jacksontj** [comment]
First off; thanks for reaching out! Glad to see more people are finding this project helpful.

I took a look and this looks pretty trivial to enable -- so I did :) https://github.com/jacksontj/promxy/pull/662
