### ISSUE TITLE
having different path_prefix per target?

### ISSUE THREAD

**Issue by keyolk** [jacksontj/promxy#658]
We are migrating our Prometheus data sources. 
Considering Promxy to maintain a consistent datasource endpoint. 
The data sources have different path prefixes, so I can't let them in the same server group.
If I want to have merged data points from those, what can I try?
Is there any workaround to resolve this?

In our use case,
some metrics are dual written to the multiple data sources,
and some metrics not.

**Comment by gavin-jeong** [comment]
found I can use relabel target __path_prefix__

**Comment by keyolk** [comment]
found I can use relabel target `__path_prefix__`
