### ISSUE TITLE
Calculation wrong when sent through promxy

### ISSUE THREAD

**Issue by SipSeb** [jacksontj/promxy#688]
## Problem

I have a Grafana data source of 2 prometheus hosts queried through promxy. And another one querying one of the prometheus hosts directly.

I have a metric returning a ISO timestamp as value, and want to use it in Grafana. To achieve this, I have to multiply the return value by 1000.

### Querying Prometheus directly
![grafana_query_prometheus](https://github.com/user-attachments/assets/0e3e5058-837a-40f9-b2b7-68681fb7b988)

### Querying Promxy
![grafana_query_promxy](https://github.com/user-attachments/assets/8d3a5c2a-0d6f-4ab7-a21b-5c3bea7f17fe)

As you can see, the return value has three more zeroes at the end than when queried directly.

## Workaround

When adding extra parentheses to the query, the return value is correct again.
![grafana_query_promxy_extra_parentheses](https://github.com/user-attachments/assets/c1621b13-007e-41e8-82d2-e1ac36bf6b09)

This seems to be wrong.

**Comment by jacksontj** [comment]
Thanks for the report! This is in fact a bug; which was introduced in #676 (so impacting v0.0.88-v0.0.90). I have a fix PR up as https://github.com/jacksontj/promxy/pull/689 which addresses this issue (and adds test cases for this).
