### ISSUE TITLE
Any puppet module open source already? can't find any

### ISSUE THREAD

**Issue by marioanton** [jacksontj/promxy#73]

**Comment by jacksontj** [comment]
Not one that I am aware of, although PRs are definitely welcome! I have container builds as part of CI for this project, but I haven't made modules/recipies for all the various configuration management systems as I haven't needed them. Promxy should be very simple to deploy, it is just a binary, a config file, and most-likely a control script. If you end up creating one, definitely feel free to contribute it!

**Comment by marioanton** [comment]
Working on it  atm, keep you posted. :)

**Comment by jacksontj** [comment]
I'm going to close this one out for now (as its been a while with no update). If you have this or if anyone else is interested in picking this up please comment and we can re-open the issue.

**Comment by jacksontj** [comment]
If anyone wants to pick this up, I have added a `deploy` directory in #145 for such things.
