### ISSUE TITLE
Configure API path for targets

### ISSUE THREAD

**Issue by hasso** [jacksontj/promxy#75]
There doesn't seem to be a way to specify API path for targets. My prometheus servers are behind proxies like this – https://proxy.host/prometheus.

**Comment by jacksontj** [comment]
@hasso thanks for opening the issue! You are correct there isn't an option for that. I just added it in #76  so you can now add `path_prefix` to a server group config and it'll prepend that string to all paths for downstream prom queries.

**Comment by propertone** [comment]
I just stumbled across this issue as well. Could you document it in the sample config file?

**Comment by jacksontj** [comment]
Sure, added in #123
