### ISSUE TITLE
Performance and Volume metrics

### ISSUE THREAD

**Issue by prabhakm** [jacksontj/promxy#78]
Hi Jackson, 
Do you have any performance numbers on promxy meaning what is the max load that you seen promxy support?
Thanks,
Prabha

**Comment by jacksontj** [comment]
Performance is a bit of a tricky question-- as it depends so much on context etc. Promxy is effectively just a proxy that is CPU bound. As for *how much* load a single host could do varies wildly based on the queries/metrics it is proxying. That being said, on my installs the CPU utilization is usually <10% -- so generally quite low.

Hopefully thats somewhat helpful? AFAIK there isn't really a standard "perf" benchmark for prom-- so making one for both would be a fairly tall order :)

**Comment by prabhakm** [comment]
:)
Thank you Jackson.
"on my installs the CPU utilization is usually <10%" => what is the settings that you have and how many metrics are scraped at what freq? possible to share some of those?

**Comment by jacksontj** [comment]
Unfortunately I'm unable to share a lot of the specifics-- but suffice it to say we have a lot of metrics (order millions) behind promxy and its humming along just fine. As far as metric scrape freq. etc.-- the main bottleneck you are going to run into on promxy/prometheus on the query side is how large your queries are. Meaning, if you query for every single data point in the last month -- it'll be significantly slower than the single most recent point (sounds obvious, but a bit hard to keep track of when writing promql).

(from the [readme](https://github.com/jacksontj/promxy#what-is-query-performance-like-with-promxy):
> Promxy's goal is to be the same performance as the slowest prometheus server it has to talk to. If you have a query that is significantly slower through promxy than on prometheus direct please open up an issue so we can get that taken care of.

Hopefully thats somewhat helpful?

**Comment by prabhakm** [comment]
Definitely helpful Jackson. Please feel free to close the issue per convenience. Thanks again
