### ISSUE TITLE
Confused about alerting and rules configurations

### ISSUE THREAD

**Issue by cullenmcdermott** [jacksontj/promxy#92]
Hi,

I'm just getting started with Prometheus and I've just started looking at this project so please pardon any ignorance. 

I'm mainly unsure how to configure recording rules and alerting in Promxy. Do these settings replace the equivalent settings in Prometheus itself? Are they in addition to them?

Also what kind of system specs are needed by Promxy compared to my Prometheus servers? Does it need to run on equivalent hardware or is it easy to scale out horizontally with multiple Promxy nodes behind a single load balancer?

Thanks!

**Comment by cullenmcdermott** [comment]
Thanks that does help. So I can use those rules in Promxy and/or in Prometheus itself? I assume it isn't a requirement to configure those rules for Promxy? For example if I just want to configure promxy as the datasource for Grafana I could do that and only use the recording rules and alerting config on the actual prometheus nodes themselves? Or if I did it that way would my recording rules not filter up to promxy so I wouldn't be able to take advantage of the precalculated metrics from them?

**Comment by jacksontj** [comment]
> So I can use those rules in Promxy and/or in Prometheus itself? 

Correct. Alerting/Recording rules are pretty basic, they just run on the configured interval and do what they are configured to do (check for an alert, calculate a metric to record). These don't need to "filter up" to promxy-- promxy itself just aggregates promql queries to the various prometheus hosts. Alerts (for example) on prometheus don't actually trigger the page -- they go through [alertmanager](https://prometheus.io/docs/alerting/alertmanager/) which aggregates those and handles the pages themselves. Recording rules running on prometheus would generate additional series which would be stored in the prometheus itself-- and as soon as those appear in the store you can query them through promxy.

Generally you only want/need to put alerts/recording rules on promxy when you need cross-prometheus aggregation.

**Comment by cullenmcdermott** [comment]
Thanks this is super helpful and clear things up quite a bit!

**Comment by jacksontj** [comment]
@cullenmcdermott glad to be of help! Definitely feel free to ask any questions as you get into using promxy :)

**Comment by thosil** [comment]
Hi,
I'm trying to setup an architecture where I have 2 x (multiple Prometheis, sending metrics to victoria-metrics ) which are queried by Promxy.
This way I have federation of multiple Prometheis + long term storage + HA + alerting rules defined for a complex setup.
But the alerts generated by Prometheus are not sent the the AlertManager by Promxy, they could be queried with promql, but I have to connect all Prometheis instances to the AlertManagers.

Is that the expected way to setup?

Thanks
