### ISSUE TITLE
Promxy exposed metrics question

### ISSUE THREAD

**Issue by hristodragolovbede** [jacksontj/promxy#95]
Hi there,

I'm trying to setup some monitoring based on the exposed metrics from promxy. One of the metrics exposed is **server_group_request_sum** and **server_group_request_count**. My understanding is that the first one represents the sum of the requests times while the latter represents the total count of the requests.

If this is correct it is not very clear what is the unit size(seconds,milliseconds,microseconds?) of the **server_group_request_sum** metric. The results I have so far doesn't make any sense to me if I assume the unit size is any of these: seconds/milliseconds/microseconds.

**Comment by jacksontj** [comment]
This is currently in nanoseconds (the base time for golang's time.Duration). I've created #96 to clean that up (set the name and unit clearly).
